-- qcs: quality controls for data
-- Generated from src/other/qcs.csv
-- Run `node backend/db/generate_qcs_sql.mjs` from project root to regenerate after editing the CSV.
--
-- place_level: NULL means the QC applies to all place levels (1 and 2).
--              An integer (1 or 2) restricts it to that specific place level.

INSERT INTO qcs (name, label_de, label_en, label_fr, label_it, table_name, place_level, is_root_level, is_project_level, is_subproject_level)
VALUES
('projectNameMissing', 'Projekte ohne Namen', 'Projects without name', 'Projets sans nom', 'Progetti senza nome', 'projects', NULL, false, true, false),
('userEmailMissing', 'Benutzer ohne Email', 'Users without email', 'Utilisateurs sans email', 'Utenti senza email', 'users', NULL, true, false, false),
('userNameMissing', 'Benutzer ohne Name', 'Users without name', 'Utilisateurs sans nom', 'Utenti senza nome', 'users', NULL, true, false, false),
('accountUserMissing', 'Konten ohne Benutzer', 'Accounts without user', 'Comptes sans utilisateur', 'Account senza utente', 'accounts', NULL, true, false, false),
('accountTypeMissing', 'Konten ohne Typ', 'Accounts without type', 'Comptes sans type', 'Account senza tipo', 'accounts', NULL, true, false, false),
('accountPeriodStartMissing', 'Konten ohne Startzeitpunkt', 'Accounts without start date', 'Comptes sans date de début', 'Account senza data di inizio', 'accounts', NULL, true, false, false),
('fieldTypesNameMissing', 'Feld-Typen ohne Namen', 'Field types without name', 'Types de champ sans nom', 'Tipi di campo senza nome', 'field_types', NULL, true, false, false),
('widgetTypesNameMissing', 'Widget-Typen ohne Namen', 'Widget types without name', 'Types de widget sans nom', 'Tipi di widget senza nome', 'widget_types', NULL, true, false, false),
('widgetsForFieldsFieldTypeMissing', 'Widgets für Felder ohne Feld-Typ', 'Widgets for fields without field type', 'Widgets pour champs sans type de champ', 'Widget per campi senza tipo di campo', 'widgets_for_fields', NULL, true, false, false),
('widgetsForFieldsWidgetTypeMissing', 'Widgets für Felder ohne Widget-Typ', 'Widgets for fields without widget type', 'Widgets pour champs sans type de widget', 'Widget per campi senza tipo di widget', 'widgets_for_fields', NULL, true, false, false),
('fieldsTableNameMissing', 'Felder ohne Tabelle', 'Fields without table', 'Champs sans table', 'Campi senza tabella', 'fields', NULL, true, false, false),
('fieldsLevelMissing', 'Ort-Felder ohne Stufe', 'Place fields without level', 'Champs de lieu sans niveau', 'Campi di luogo senza livello', 'fields', NULL, true, false, false),
('fieldsNameMissing', 'Felder ohne Namen', 'Fields without name', 'Champs sans nom', 'Campi senza nome', 'fields', NULL, true, false, false),
('fieldsFieldTypeMissing', 'Felder ohne Feld-Typ', 'Fields without field type', 'Champs sans type de champ', 'Campi senza tipo di campo', 'fields', NULL, true, false, false),
('fieldsWidgetTypeMissing', 'Felder ohne Widget', 'Fields without widget', 'Champs sans widget', 'Campi senza widget', 'fields', NULL, true, false, false),
('placeLevelsLevelMissing', 'Ort-Stufen ohne Stufe', 'Place levels without level', 'Niveaux de lieu sans niveau', 'Livelli di luogo senza livello', 'place_levels', NULL, false, true, false),
('placeLevelsDeMissing', 'Ort-Stufen ohne Deutsche Namen', 'Place levels without German name', 'Niveaux de lieu sans nom allemand', 'Livelli di luogo senza nome tedesco', 'place_levels', NULL, false, true, false),
('placeLevelsEnMissing', 'Ort-Stufen ohne Englische Namen', 'Place levels without English name', 'Niveaux de lieu sans nom anglais', 'Livelli di luogo senza nome inglese', 'place_levels', NULL, false, true, false),
('placeLevelsFrMissing', 'Ort-Stufen ohne Französische Namen', 'Place levels without French name', 'Niveaux de lieu sans nom français', 'Livelli di luogo senza nome francese', 'place_levels', NULL, false, true, false),
('placeLevelsItMissing', 'Ort-Stufen ohne Italienische Namen', 'Place levels without Italian name', 'Niveaux de lieu sans nom italien', 'Livelli di luogo senza nome italiano', 'place_levels', NULL, false, true, false),
('observationImportsGeometrieMissing', 'Beobachtungs-Importe ohne Geometrie-Feld', 'Observation imports without geometry field', 'Importations d''observations sans champ de géométrie', 'Importazioni di osservazioni senza campo geometria', 'observation_imports', NULL, false, true, false),
('observationImportsCrsMissing', 'Beobachtungs-Importe ohne KBS', 'Observation imports without CRS', 'Importations d''observations sans SCR', 'Importazioni di osservazioni senza SRC', 'observation_imports', NULL, false, true, false),
('observationImportsLabelMissing', 'Beobachtungs-Importe ohne Beschriftung', 'Observation imports without label', 'Importations d''observations sans étiquette', 'Importazioni di osservazioni senza etichetta', 'observation_imports', NULL, false, true, false),
('observationImportsNameMissing', 'Beobachtungs-Importe ohne Name', 'Observation imports without name', 'Importations d''observations sans nom', 'Importazioni di osservazioni senza nome', 'observation_imports', NULL, false, true, false),
('wmsServicesUrlMissing', 'WMS-Dienste ohne URL', 'WMS services without URL', 'Services WMS sans URL', 'Servizi WMS senza URL', 'wms_services', NULL, false, true, false),
('wmsServicesServiceLayersMissing', 'WMS-Dienste ohne Ebenen', 'WMS services without layers', 'Services WMS sans couches', 'Servizi WMS senza livelli', 'wms_services', NULL, false, true, false),
('wmsLayersLayerMissing', 'WMS-Ebenen ohne Ebene', 'WMS layers without layer', 'Couches WMS sans couche', 'Layer WMS senza layer', 'wms_layers', NULL, false, true, false),
('wfsServicesUrlMissing', 'WFS-Dienste ohne URL', 'WFS services without URL', 'Services WFS sans URL', 'Servizi WFS senza URL', 'wfs_services', NULL, false, true, false),
('wfsServicesServiceLayersMissing', 'WFS-Dienste ohne Ebenen', 'WFS services without layers', 'Services WFS sans couches', 'Servizi WFS senza livelli', 'wfs_services', NULL, false, true, false),
('vectorLayersDisplaysMissing', 'Vektor-Ebenen ohne Anzeigen', 'Vector layers without display', 'Couches vectorielles sans affichage', 'Layer vettoriali senza visualizzazione', 'vector_layers', NULL, false, true, false),
('vectorLayersTypeMissing', 'Vektor-Ebenen ohne Typ', 'Vector layers without type', 'Couches vectorielles sans type', 'Layer vettoriali senza tipo', 'vector_layers', NULL, false, true, false),
('vectorLayersNameMissing', 'Vektor-Ebenen ohne Name', 'Vector layers without name', 'Couches vectorielles sans nom', 'Layer vettoriali senza nome', 'vector_layers', NULL, false, true, false),
('vectorLayersPresentationMissing', 'Vektor-Ebene ohne «Presentation»', 'Vector layer without presentation', 'Couche vectorielle sans présentation', 'Layer vettoriale senza presentazione', 'vector_layers', NULL, false, true, false),
('chartsSubjectMissing', 'Diagramme ohne Themen', 'Charts without subjects', 'Graphiques sans sujets', 'Grafici senza soggetti', 'charts', NULL, false, false, true),
('chartsTypeMissing', 'Diagramme ohne Typ', 'Charts without type', 'Graphiques sans type', 'Grafici senza tipo', 'charts', NULL, false, false, true),
('chartsNameMissing', 'Diagramme ohne Name', 'Charts without name', 'Graphiques sans nom', 'Grafici senza nome', 'charts', NULL, false, false, true),
('chartSubjectsNameMissing', 'Diagramm-Themen ohne Name', 'Chart subjects without name', 'Sujets de graphique sans nom', 'Soggetti grafici senza nome', 'chart_subjects', NULL, false, false, true),
('chartSubjectsTableMissing', 'Diagramm-Themen ohne Tabelle', 'Chart subjects without table', 'Sujets de graphique sans table', 'Soggetti grafici senza tabella', 'chart_subjects', NULL, false, false, true),
('chartSubjectsCalcMethodMissing', 'Diagramm-Themen ohne Berechnungsmethode', 'Chart subjects without calculation method', 'Sujets de graphique sans méthode de calcul', 'Soggetti grafici senza metodo di calcolo', 'chart_subjects', NULL, false, false, true),
('chartSubjectsStrokeOrFillMissing', 'Diagramm-Themen ohne Farbe', 'Chart subjects without color', 'Sujets de graphique sans couleur', 'Soggetti grafici senza colore', 'chart_subjects', NULL, false, false, true),
('projectCrsCrsMissing', 'Projekt-KBS ohne KBS', 'Project CRS without CRS', 'CRS de projet sans CRS', 'CRS di progetto senza CRS', 'project_crs', NULL, false, true, false),
('unitsNameMissing', 'Einheiten ohne Name', 'Units without name', 'Unités sans nom', 'Unità senza nome', 'units', NULL, false, true, false),
('unitsTypeMissing', 'Einheiten ohne Typ', 'Units without type', 'Unités sans type', 'Unità senza tipo', 'units', NULL, false, true, false),
('taxonomiesNameMissing', 'Taxonomien ohne Name', 'Taxonomies without name', 'Taxonomies sans nom', 'Tassonomie senza nome', 'taxonomies', NULL, false, true, false),
('taxonomiesTypeMissing', 'Taxonomien ohne Typ', 'Taxonomies without type', 'Taxonomies sans type', 'Tassonomie senza tipo', 'taxonomies', NULL, false, true, false),
('taxonomiesTaxaMissing', 'Taxonomien ohne Taxa', 'Taxonomies without taxa', 'Taxonomies sans taxons', 'Tassonomie senza taxa', 'taxonomies', NULL, false, true, false),
('taxaNameMissing', 'Taxon ohne Namen', 'Taxon without name', 'Taxon sans nom', 'Taxon senza nome', 'taxa', NULL, false, true, false),
('listsNameMissing', 'Listen ohne Namen', 'Lists without name', 'Listes sans nom', 'Liste senza nome', 'lists', NULL, false, true, false),
('listsValueTypeMissing', 'Listen ohne Wert-Typ', 'Lists without value type', 'Listes sans type de valeur', 'Liste senza tipo di valore', 'lists', NULL, false, true, false),
('listsValuesMissing', 'Listen ohne Werte', 'Lists without values', 'Listes sans valeurs', 'Liste senza valori', 'lists', NULL, false, true, false),
('projectUsersUserMissing', 'Projekt-Benutzer ohne Benutzer', 'Project users without user', 'Utilisateurs de projet sans utilisateur', 'Utenti di progetto senza utente', 'project_users', NULL, false, true, false),
('projectUsersRoleMissing', 'Projekt-Benutzer ohne Rolle', 'Project users without role', 'Utilisateurs de projet sans rôle', 'Utenti di progetto senza ruolo', 'project_users', NULL, false, true, false),
('projectReportsYearMissing', 'Projekt-Berichte ohne Jahr', 'Project reports without year', 'Rapports de projet sans année', 'Rapporti di progetto senza anno', 'project_reports', NULL, false, true, false),
('subprojectReportsYearMissing', 'Teil-Projekt-Berichte ohne Jahr', 'Subproject reports without year', 'Rapports de sous-projet sans année', 'Rapporti di sottoprogetto senza anno', 'subproject_reports', NULL, false, false, true),
('subprojectReportsDataMissing', 'Teil-Projekt-Berichte ohne Daten', 'Subproject reports without data', 'Rapports de sous-projet sans données', 'Rapporti di sottoprogetto senza dati', 'subproject_reports', NULL, false, false, true),
('projectReportDesignsNameMissing', 'Projekt-Bericht-Designs ohne Name', 'Project report designs without name', 'Designs de rapport de projet sans nom', 'Design di rapporto di progetto senza nome', 'project_report_designs', NULL, false, true, false),
('projectReportDesignsDesignMissing', 'Projekt-Bericht-Designs ohne Design', 'Project report designs without design', 'Designs de rapport de projet sans design', 'Design di rapporto di progetto senza design', 'project_report_designs', NULL, false, true, false),
('subprojectReportDesignsNameMissing', 'Teil-Projekt-Bericht-Designs ohne Name', 'Subproject report designs without name', 'Designs de rapport de sous-projet sans nom', 'Design di rapporto di sottoprogetto senza nome', 'subproject_report_designs', NULL, false, false, true),
('subprojectReportDesignsDesignMissing', 'Teil-Projekt-Bericht-Designs ohne Design', 'Subproject report designs without design', 'Designs de rapport de sous-projet sans design', 'Design di rapporto di sottoprogetto senza design', 'subproject_report_designs', NULL, false, false, true),
('subprojectUserUserMissing', 'Teil-Projekt-Benutzer ohne Benutzer', 'Subproject users without user', 'Utilisateurs de sous-projet sans utilisateur', 'Utenti di sottoprogetto senza utente', 'subproject_users', NULL, false, false, true),
('subprojectUserRoleMissing', 'Teil-Projekt-Benutzer ohne Rolle', 'Subproject users without role', 'Utilisateurs de sous-projet sans rôle', 'Utenti di sottoprogetto senza ruolo', 'subproject_users', NULL, false, false, true),
('subprojectTaxaTaxonMissing', 'Teil-Projekt-Taxa ohne Taxon', 'Subproject taxa without taxon', 'Taxons de sous-projet sans taxon', 'Taxa di sottoprogetto senza taxon', 'subproject_taxa', NULL, false, false, true),
('goalsYearMissing', 'Ziele ohne Jahr', 'Goals without year', 'Objectifs sans année', 'Obiettivi senza anno', 'goals', NULL, false, false, true),
('goalsNameMissing', 'Ziele ohne Namen', 'Goals without name', 'Objectifs sans nom', 'Obiettivi senza nome', 'goals', NULL, false, false, true),
('goalsReportMissing', 'Ziele ohne Bericht', 'Goals without report', 'Objectifs sans rapport', 'Obiettivi senza rapporto', 'goals', NULL, false, false, true),
('subprojectsNameMissing', 'Teil-Projekt ohne Name', 'Subproject without name', 'Sous-projet sans nom', 'Sottoprogetto senza nome', 'subprojects', NULL, false, false, true),
('subprojectsStartYearMissing', 'Teil-Projekt ohne Startjahr', 'Subproject without start year', 'Sous-projet sans année de début', 'Sottoprogetto senza anno di inizio', 'subprojects', NULL, false, false, true),
('subprojectsPlaces1Missing', 'Teil-Projekt ohne Orte', 'Subproject without places', 'Sous-projet sans lieux', 'Sottoprogetto senza luoghi', 'subprojects', NULL, false, false, true),
('placesGeometryMissing', 'Orte (relevante und aktuell existierende) ohne Geometrie', 'Places (relevant and currently existing) without geometry', 'Lieux (pertinents et actuellement existants) sans géométrie', 'Luoghi (rilevanti e attualmente esistenti) senza geometria', 'places', NULL, false, false, true),
('placesSinceMissing', 'Orte (relevante und aktuell existierende) ohne Seit wann', 'Places (relevant and currently existing) without since date', 'Lieux (pertinents et actuellement existants) sans date de début', 'Luoghi (rilevanti e attualmente esistenti) senza data di inizio', 'places', NULL, false, false, true),
('placesNameMissing', 'Orte (relevante und aktuell existierende) ohne Name', 'Places (relevant and currently existing) without name', 'Lieux (pertinents et actuellement existants) sans nom', 'Luoghi (rilevanti e attualmente esistenti) senza nome', 'places', NULL, false, false, true),
('placesFilesMissing', 'Orte (relevante und aktuell existierende) ohne Dateien', 'Places (relevant and currently existing) without files', 'Lieux (pertinents et actuellement existants) sans fichiers', 'Luoghi (rilevanti e attualmente esistenti) senza file', 'places', NULL, false, false, true),
('placesChecksMissing', 'Orte (relevante und aktuell existierende) ohne Kontrollen', 'Places (relevant and currently existing) without checks', 'Lieux (pertinents et actuellement existants) sans contrôles', 'Luoghi (rilevanti e attualmente esistenti) senza controlli', 'places', NULL, false, false, true),
('placesChecksMissingInYear', 'Orte (relevante und aktuell existierende) ohne Kontrolle in Jahr', 'Places (relevant and currently existing) without check in year', 'Lieux (pertinents et actuellement existants) sans contrôle dans l''année', 'Luoghi (rilevanti e attualmente esistenti) senza controllo nell''anno', 'places', NULL, false, false, true),
('placesActionsMissing', 'Orte (relevante und aktuell existierende) ohne Massnahmen', 'Places (relevant and currently existing) without actions', 'Lieux (pertinents et actuellement existants) sans actions', 'Luoghi (rilevanti e attualmente esistenti) senza azioni', 'places', NULL, false, false, true),
('placesActionsMissingInYear', 'Orte (relevante und aktuell existierende) ohne Massnahme in Jahr', 'Places (relevant and currently existing) without action in year', 'Lieux (pertinents et actuellement existants) sans action dans l''année', 'Luoghi (rilevanti e attualmente esistenti) senza azione nell''anno', 'places', NULL, false, false, true),
('placesReportsMissing', 'Orte (relevante und aktuell existierende) ohne Berichte', 'Places (relevant and currently existing) without reports', 'Lieux (pertinents et actuellement existants) sans rapports', 'Luoghi (rilevanti e attualmente esistenti) senza rapporti', 'places', NULL, false, false, true),
('placesReportsMissingInYear', 'Orte (relevante und aktuell existierende) ohne Bericht in Jahr', 'Places (relevant and currently existing) without report in year', 'Lieux (pertinents et actuellement existants) sans rapport dans l''année', 'Luoghi (rilevanti e attualmente esistenti) senza rapporto nell''anno', 'places', NULL, false, false, true),
('places1Places2Missing', 'Orte (relevante und aktuell existierende) Stufe 1 ohne Stufe 2', 'Places (relevant and currently existing) level 1 without level 2', 'Lieux (pertinents et actuellement existants) niveau 1 sans niveau 2', 'Luoghi (rilevanti e attualmente esistenti) livello 1 senza livello 2', 'places', 1, false, false, true),
('placeUsersUserMissing', 'Ort-Benutzer ohne Benutzer', 'Place users without user', 'Utilisateurs de lieu sans utilisateur', 'Utenti di luogo senza utente', 'place_users', NULL, false, false, true),
('placeUsersRoleMissing', 'Ort-Benutzer ohne Rolle', 'Place users without role', 'Utilisateurs de lieu sans rôle', 'Utenti di luogo senza ruolo', 'place_users', NULL, false, false, true),
('checksDateMissing', 'Kontrollen (relevante) ohne Datum', 'Checks (relevant) without date', 'Contrôles (pertinents) sans date', 'Controlli (rilevanti) senza data', 'checks', NULL, false, false, true),
('checksGeometryMissing', 'Kontrollen (relevante) ohne Geometrie', 'Checks (relevant) without geometry', 'Contrôles (pertinents) sans géométrie', 'Controlli (rilevanti) senza geometria', 'checks', NULL, false, false, true),
('checksQuantitiesMissing', 'Kontrollen (relevante) ohne Menge', 'Checks (relevant) without quantity', 'Contrôles (pertinents) sans quantité', 'Controlli (rilevanti) senza quantità', 'checks', NULL, false, false, true),
('checksTaxaMissing', 'Kontrollen (relevante) ohne Taxa', 'Checks (relevant) without taxa', 'Contrôles (pertinents) sans taxons', 'Controlli (rilevanti) senza taxa', 'checks', NULL, false, false, true),
('checksReportMissingInYear', 'Kontrollen (relevante) ohne Bericht in Jahr', 'Checks (relevant) without report in year', 'Contrôles (pertinents) sans rapport dans l''année', 'Controlli (rilevanti) senza rapporto nell''anno', 'checks', NULL, false, false, true),
('checksFilesMissing', 'Kontrollen (relevante) ohne Datei', 'Checks (relevant) without file', 'Contrôles (pertinents) sans fichier', 'Controlli (rilevanti) senza file', 'checks', NULL, false, false, true),
('actionsDateMissing', 'Massnahmen (relevante) ohne Datum', 'Actions (relevant) without date', 'Actions (pertinentes) sans date', 'Azioni (rilevanti) senza data', 'actions', NULL, false, false, true),
('actionsGeometryMissing', 'Massnahmen (relevante) ohne Geometrie', 'Actions (relevant) without geometry', 'Actions (pertinentes) sans géométrie', 'Azioni (rilevanti) senza geometria', 'actions', NULL, false, false, true),
('actionsQuantitiesMissing', 'Massnahmen (relevante) ohne Menge', 'Actions (relevant) without quantity', 'Actions (pertinentes) sans quantité', 'Azioni (rilevanti) senza quantità', 'actions', NULL, false, false, true),
('actionsTaxaMissing', 'Massnahmen (relevante) ohne Taxa', 'Actions (relevant) without taxa', 'Actions (pertinentes) sans taxons', 'Azioni (rilevanti) senza taxa', 'actions', NULL, false, false, true),
('actionsReportMissingInYear', 'Massnahmen (relevante) ohne Bericht in Jahr', 'Actions (relevant) without report in year', 'Actions (pertinentes) sans rapport dans l''année', 'Azioni (rilevanti) senza rapporto nell''anno', 'actions', NULL, false, false, true),
('actionsFilesMissing', 'Massnahmen (relevante) ohne Datei', 'Actions (relevant) without file', 'Actions (pertinentes) sans fichier', 'Azioni (rilevanti) senza file', 'actions', NULL, false, false, true),
('placeReportQuantitiesNoDefault', 'Ort-Bericht-Mengen: Standard-Einheit nicht verwendet', 'Place report quantities: default unit not used', 'Quantités de rapport de lieu : unité par défaut non utilisée', 'Quantità di rapporto di luogo: unità predefinita non utilizzata', 'places', NULL, false, false, true),
('checkQuantitiesNoDefault', 'Kontroll-Mengen: Standard-Einheit nicht verwendet', 'Check quantities: default unit not used', 'Quantités de contrôle : unité par défaut non utilisée', 'Quantità di controllo: unità predefinita non utilizzata', 'checks', NULL, false, false, true),
('checkReportQuantitiesNoDefault', 'Kontroll-Bericht-Mengen: Standard-Einheit nicht verwendet', 'Check report quantities: default unit not used', 'Quantités de rapport de contrôle : unité par défaut non utilisée', 'Quantità di rapporto di controllo: unità predefinita non utilizzata', 'checks', NULL, false, false, true),
('checkTaxonQuantitiesNoDefault', 'Kontroll-Taxon-Mengen: Standard-Einheit nicht verwendet', 'Check taxon quantities: default unit not used', 'Quantités de taxon de contrôle : unité par défaut non utilisée', 'Quantità di taxon di controllo: unità predefinita non utilizzata', 'checks', NULL, false, false, true),
('actionQuantitiesNoDefault', 'Massnahmen-Mengen: Standard-Einheit nicht verwendet', 'Action quantities: default unit not used', 'Quantités d''actions : unité par défaut non utilisée', 'Quantità di azioni: unità predefinita non utilizzata', 'actions', NULL, false, false, true),
('actionReportQuantitiesNoDefault', 'Massnahmen-Bericht-Mengen: Standard-Einheit nicht verwendet', 'Action report quantities: default unit not used', 'Quantités de rapport d''actions : unité par défaut non utilisée', 'Quantità di rapporto di azioni: unità predefinita non utilizzata', 'actions', NULL, false, false, true),
('actionTaxonQuantitiesNoDefault', 'Massnahmen-Taxon-Mengen: Standard-Einheit nicht verwendet', 'Action taxon quantities: default unit not used', 'Quantités de taxon d''actions : unité par défaut non utilisée', 'Quantità di taxon di azioni: unità predefinita non utilizzata', 'actions', NULL, false, false, true)
ON CONFLICT (name) DO UPDATE SET
  label_de            = EXCLUDED.label_de,
  label_en            = EXCLUDED.label_en,
  label_fr            = EXCLUDED.label_fr,
  label_it            = EXCLUDED.label_it,
  table_name          = EXCLUDED.table_name,
  place_level         = EXCLUDED.place_level,
  is_root_level       = EXCLUDED.is_root_level,
  is_project_level    = EXCLUDED.is_project_level,
  is_subproject_level = EXCLUDED.is_subproject_level;
