export const excludedDisplayFields = new Set(['sys_period', 'created_at', 'label'])

export const excludedRestoreFields = new Set([
  'place_level_id',
  'account_id',
  'project_id',
  'label',
  'sys_period',
  'created_at',
  'updated_at',
  'updated_by',
])

export const preferredOrder = [
  'level',
  'name_singular_de',
  'name_plural_de',
  'name_singular_en',
  'name_plural_en',
  'name_singular_fr',
  'name_plural_fr',
  'name_singular_it',
  'name_plural_it',
  'observations',
  'place_files',
  'place_users_in_place',
  'place_files_in_place',
  'checks',
  'check_quantities',
  'check_quantities_in_check',
  'check_taxa',
  'check_taxa_in_check',
  'check_files',
  'check_files_in_check',
  'check_reports',
  'check_report_quantities',
  'check_report_quantities_in_report',
  'actions',
  'action_quantities',
  'action_quantities_in_action',
  'action_taxa',
  'action_taxa_in_action',
  'action_files',
  'action_files_in_action',
  'action_reports',
  'action_report_quantities',
  'action_report_quantities_in_report',
]
