// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_place_action_reports_history */
export default interface TemplatePublicPlaceActionReportsHistory {
  place_action_report_id: string;

  account_id: string | null;

  place_id: string | null;

  year: number | null;

  data: unknown | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_place_action_reports_history */
export interface TemplatePublicPlaceActionReportsHistoryInitializer {
  place_action_report_id: string;

  account_id?: string | null;

  place_id?: string | null;

  year?: number | null;

  data?: unknown | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_place_action_reports_history */
export interface TemplatePublicPlaceActionReportsHistoryMutator {
  place_action_report_id?: string;

  account_id?: string | null;

  place_id?: string | null;

  year?: number | null;

  data?: unknown | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
