// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_project_report_designs_history */
export default interface TemplatePublicProjectReportDesignsHistory {
  project_report_design_id: string;

  account_id: string | null;

  project_id: string | null;

  name: string | null;

  label: string | null;

  active: boolean | null;

  design: unknown | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_project_report_designs_history */
export interface TemplatePublicProjectReportDesignsHistoryInitializer {
  project_report_design_id: string;

  account_id?: string | null;

  project_id?: string | null;

  name?: string | null;

  label?: string | null;

  active?: boolean | null;

  design?: unknown | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_project_report_designs_history */
export interface TemplatePublicProjectReportDesignsHistoryMutator {
  project_report_design_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  name?: string | null;

  label?: string | null;

  active?: boolean | null;

  design?: unknown | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
