// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as public_ProjectTypesEnum } from '../public/ProjectTypesEnum';

/** Represents the table partman.template_public_projects_history */
export default interface TemplatePublicProjectsHistory {
  project_id: string;

  account_id: string | null;

  name: string | null;

  label: string | null;

  type: public_ProjectTypesEnum | null;

  subproject_name_singular: string | null;

  subproject_name_plural: string | null;

  subproject_name_singular_en: string | null;

  subproject_name_plural_en: string | null;

  subproject_name_singular_fr: string | null;

  subproject_name_plural_fr: string | null;

  subproject_name_singular_it: string | null;

  subproject_name_plural_it: string | null;

  subproject_order_by: string | null;

  places_label_by: string | null;

  places_order_by: string | null;

  goals_label_by: string | null;

  goal_reports_label_by: string | null;

  goal_reports_order_by: string | null;

  actions_default_unit_id: string | null;

  checks_default_unit_id: string | null;

  check_taxa_default_unit_id: string | null;

  action_taxa_default_unit_id: string | null;

  check_reports_default_unit_id: string | null;

  action_reports_default_unit_id: string | null;

  values_on_multiple_levels: string | null;

  multiple_action_quantities_on_same_level: string | null;

  multiple_check_quantities_on_same_level: string | null;

  wms_layers: boolean | null;

  vector_layers: boolean | null;

  project_reports: boolean | null;

  subproject_reports: boolean | null;

  goals: boolean | null;

  occurrences: boolean | null;

  taxa: boolean | null;

  charts: boolean | null;

  enable_histories: boolean | null;

  data: unknown | null;

  files_offline: boolean | null;

  files_active_projects: boolean | null;

  project_files_in_project: boolean | null;

  files_active_subprojects: boolean | null;

  subproject_files_in_subproject: boolean | null;

  map_presentation_crs: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_projects_history */
export interface TemplatePublicProjectsHistoryInitializer {
  project_id: string;

  account_id?: string | null;

  name?: string | null;

  label?: string | null;

  type?: public_ProjectTypesEnum | null;

  subproject_name_singular?: string | null;

  subproject_name_plural?: string | null;

  subproject_name_singular_en?: string | null;

  subproject_name_plural_en?: string | null;

  subproject_name_singular_fr?: string | null;

  subproject_name_plural_fr?: string | null;

  subproject_name_singular_it?: string | null;

  subproject_name_plural_it?: string | null;

  subproject_order_by?: string | null;

  places_label_by?: string | null;

  places_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  actions_default_unit_id?: string | null;

  checks_default_unit_id?: string | null;

  check_taxa_default_unit_id?: string | null;

  action_taxa_default_unit_id?: string | null;

  check_reports_default_unit_id?: string | null;

  action_reports_default_unit_id?: string | null;

  values_on_multiple_levels?: string | null;

  multiple_action_quantities_on_same_level?: string | null;

  multiple_check_quantities_on_same_level?: string | null;

  wms_layers?: boolean | null;

  vector_layers?: boolean | null;

  project_reports?: boolean | null;

  subproject_reports?: boolean | null;

  goals?: boolean | null;

  occurrences?: boolean | null;

  taxa?: boolean | null;

  charts?: boolean | null;

  enable_histories?: boolean | null;

  data?: unknown | null;

  files_offline?: boolean | null;

  files_active_projects?: boolean | null;

  project_files_in_project?: boolean | null;

  files_active_subprojects?: boolean | null;

  subproject_files_in_subproject?: boolean | null;

  map_presentation_crs?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_projects_history */
export interface TemplatePublicProjectsHistoryMutator {
  project_id?: string;

  account_id?: string | null;

  name?: string | null;

  label?: string | null;

  type?: public_ProjectTypesEnum | null;

  subproject_name_singular?: string | null;

  subproject_name_plural?: string | null;

  subproject_name_singular_en?: string | null;

  subproject_name_plural_en?: string | null;

  subproject_name_singular_fr?: string | null;

  subproject_name_plural_fr?: string | null;

  subproject_name_singular_it?: string | null;

  subproject_name_plural_it?: string | null;

  subproject_order_by?: string | null;

  places_label_by?: string | null;

  places_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  actions_default_unit_id?: string | null;

  checks_default_unit_id?: string | null;

  check_taxa_default_unit_id?: string | null;

  action_taxa_default_unit_id?: string | null;

  check_reports_default_unit_id?: string | null;

  action_reports_default_unit_id?: string | null;

  values_on_multiple_levels?: string | null;

  multiple_action_quantities_on_same_level?: string | null;

  multiple_check_quantities_on_same_level?: string | null;

  wms_layers?: boolean | null;

  vector_layers?: boolean | null;

  project_reports?: boolean | null;

  subproject_reports?: boolean | null;

  goals?: boolean | null;

  occurrences?: boolean | null;

  taxa?: boolean | null;

  charts?: boolean | null;

  enable_histories?: boolean | null;

  data?: unknown | null;

  files_offline?: boolean | null;

  files_active_projects?: boolean | null;

  project_files_in_project?: boolean | null;

  files_active_subprojects?: boolean | null;

  subproject_files_in_subproject?: boolean | null;

  map_presentation_crs?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
