// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as public_ObservationImportsGeometryMethodsEnum } from '../public/ObservationImportsGeometryMethodsEnum';

/** Represents the table partman.template_public_observation_imports_history */
export default interface TemplatePublicObservationImportsHistory {
  observation_import_id: string;

  account_id: string | null;

  subproject_id: string | null;

  created_time: Date | null;

  inserted_count: number | null;

  id_field: string | null;

  geometry_method: public_ObservationImportsGeometryMethodsEnum | null;

  geojson_geometry_field: string | null;

  x_coordinate_field: string | null;

  y_coordinate_field: string | null;

  crs: string | null;

  label_creation: unknown | null;

  name: string | null;

  attribution: string | null;

  previous_import: string | null;

  download_from_gbif: boolean | null;

  gbif_filters: unknown | null;

  gbif_download_key: string | null;

  gbif_error: string | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_observation_imports_history */
export interface TemplatePublicObservationImportsHistoryInitializer {
  observation_import_id: string;

  account_id?: string | null;

  subproject_id?: string | null;

  created_time?: Date | null;

  inserted_count?: number | null;

  id_field?: string | null;

  geometry_method?: public_ObservationImportsGeometryMethodsEnum | null;

  geojson_geometry_field?: string | null;

  x_coordinate_field?: string | null;

  y_coordinate_field?: string | null;

  crs?: string | null;

  label_creation?: unknown | null;

  name?: string | null;

  attribution?: string | null;

  previous_import?: string | null;

  download_from_gbif?: boolean | null;

  gbif_filters?: unknown | null;

  gbif_download_key?: string | null;

  gbif_error?: string | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_observation_imports_history */
export interface TemplatePublicObservationImportsHistoryMutator {
  observation_import_id?: string;

  account_id?: string | null;

  subproject_id?: string | null;

  created_time?: Date | null;

  inserted_count?: number | null;

  id_field?: string | null;

  geometry_method?: public_ObservationImportsGeometryMethodsEnum | null;

  geojson_geometry_field?: string | null;

  x_coordinate_field?: string | null;

  y_coordinate_field?: string | null;

  crs?: string | null;

  label_creation?: unknown | null;

  name?: string | null;

  attribution?: string | null;

  previous_import?: string | null;

  download_from_gbif?: boolean | null;

  gbif_filters?: unknown | null;

  gbif_download_key?: string | null;

  gbif_error?: string | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
