// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_field_types_history */
export default interface TemplatePublicFieldTypesHistory {
  field_type_id: string;

  name: string | null;

  sort: number | null;

  comment: string | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_field_types_history */
export interface TemplatePublicFieldTypesHistoryInitializer {
  field_type_id: string;

  name?: string | null;

  sort?: number | null;

  comment?: string | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_field_types_history */
export interface TemplatePublicFieldTypesHistoryMutator {
  field_type_id?: string;

  name?: string | null;

  sort?: number | null;

  comment?: string | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
