// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_checks_history */
export default interface TemplatePublicChecksHistory {
  check_id: string;

  account_id: string | null;

  place_id: string | null;

  date: Date | null;

  data: unknown | null;

  geometry: unknown | null;

  bbox: unknown | null;

  relevant_for_reports: boolean | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_checks_history */
export interface TemplatePublicChecksHistoryInitializer {
  check_id: string;

  account_id?: string | null;

  place_id?: string | null;

  date?: Date | null;

  data?: unknown | null;

  geometry?: unknown | null;

  bbox?: unknown | null;

  relevant_for_reports?: boolean | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_checks_history */
export interface TemplatePublicChecksHistoryMutator {
  check_id?: string;

  account_id?: string | null;

  place_id?: string | null;

  date?: Date | null;

  data?: unknown | null;

  geometry?: unknown | null;

  bbox?: unknown | null;

  relevant_for_reports?: boolean | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
