// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_places_history */
export default interface TemplatePublicPlacesHistory {
  place_id: string;

  account_id: string | null;

  subproject_id: string | null;

  parent_id: string | null;

  level: number | null;

  since: number | null;

  until: number | null;

  data: unknown | null;

  geometry: unknown | null;

  bbox: unknown | null;

  relevant_for_reports: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  sys_period: string;
}

/** Represents the initializer for the table partman.template_public_places_history */
export interface TemplatePublicPlacesHistoryInitializer {
  place_id: string;

  account_id?: string | null;

  subproject_id?: string | null;

  parent_id?: string | null;

  level?: number | null;

  since?: number | null;

  until?: number | null;

  data?: unknown | null;

  geometry?: unknown | null;

  bbox?: unknown | null;

  relevant_for_reports?: boolean | null;

  label?: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;

  sys_period: string;
}

/** Represents the mutator for the table partman.template_public_places_history */
export interface TemplatePublicPlacesHistoryMutator {
  place_id?: string;

  account_id?: string | null;

  subproject_id?: string | null;

  parent_id?: string | null;

  level?: number | null;

  since?: number | null;

  until?: number | null;

  data?: unknown | null;

  geometry?: unknown | null;

  bbox?: unknown | null;

  relevant_for_reports?: boolean | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  sys_period?: string;
}
