// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_project_crs_history */
export default interface TemplatePublicProjectCrsHistory {
  project_crs_id: string;

  crs_id: string | null;

  project_id: string | null;

  account_id: string | null;

  code: string | null;

  name: string | null;

  proj4: string | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_project_crs_history */
export interface TemplatePublicProjectCrsHistoryInitializer {
  project_crs_id: string;

  crs_id?: string | null;

  project_id?: string | null;

  account_id?: string | null;

  code?: string | null;

  name?: string | null;

  proj4?: string | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_project_crs_history */
export interface TemplatePublicProjectCrsHistoryMutator {
  project_crs_id?: string;

  crs_id?: string | null;

  project_id?: string | null;

  account_id?: string | null;

  code?: string | null;

  name?: string | null;

  proj4?: string | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
