// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_users_history */
export default interface TemplatePublicUsersHistory {
  user_id: string;

  name: string | null;

  email: string | null;

  email_verified: boolean | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table partman.template_public_users_history */
export interface TemplatePublicUsersHistoryInitializer {
  user_id: string;

  name?: string | null;

  email?: string | null;

  email_verified?: boolean | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the mutator for the table partman.template_public_users_history */
export interface TemplatePublicUsersHistoryMutator {
  user_id?: string;

  name?: string | null;

  email?: string | null;

  email_verified?: boolean | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;
}
