// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_goal_reports_history */
export default interface TemplatePublicGoalReportsHistory {
  goal_report_id: string;

  account_id: string | null;

  goal_id: string | null;

  data: unknown | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_goal_reports_history */
export interface TemplatePublicGoalReportsHistoryInitializer {
  goal_report_id: string;

  account_id?: string | null;

  goal_id?: string | null;

  data?: unknown | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_goal_reports_history */
export interface TemplatePublicGoalReportsHistoryMutator {
  goal_report_id?: string;

  account_id?: string | null;

  goal_id?: string | null;

  data?: unknown | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
