// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table partman.template_public_check_quantities_history */
export default interface TemplatePublicCheckQuantitiesHistory {
  check_quantity_id: string;

  account_id: string | null;

  check_id: string | null;

  unit_id: string | null;

  quantity_integer: number | null;

  quantity_numeric: number | null;

  quantity_text: string | null;

  label: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table partman.template_public_check_quantities_history */
export interface TemplatePublicCheckQuantitiesHistoryInitializer {
  check_quantity_id: string;

  account_id?: string | null;

  check_id?: string | null;

  unit_id?: string | null;

  quantity_integer?: number | null;

  quantity_numeric?: number | null;

  quantity_text?: string | null;

  label?: string | null;

  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table partman.template_public_check_quantities_history */
export interface TemplatePublicCheckQuantitiesHistoryMutator {
  check_quantity_id?: string;

  account_id?: string | null;

  check_id?: string | null;

  unit_id?: string | null;

  quantity_integer?: number | null;

  quantity_numeric?: number | null;

  quantity_text?: string | null;

  label?: string | null;

  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
