// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';

/** Identifier type for public.accounts */
export type AccountsAccountId = string & { __brand: 'public.accounts' };

/**
 * Represents the table public.accounts
 * Goal: earn money. Separate from users to allow for multiple accounts per user. Enables seeing the account history.
 */
export default interface Accounts {
  account_id: AccountsAccountId;

  /** user that owns the account. null for accounts that are not owned by a user */
  user_id: UsersUserId | null;

  /** type of account: "free", "basic", "premium"? (TODO: needs to be defined) */
  type: string | null;

  period_start: Date | null;

  period_end: Date | null;

  /** Used to label projects in lists. Either "name" or the name of a key in the data field. Assumed value if is null is "name" */
  projects_label_by: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.accounts
 * Goal: earn money. Separate from users to allow for multiple accounts per user. Enables seeing the account history.
 */
export interface AccountsInitializer {
  /** Default value: uuid_generate_v7() */
  account_id?: AccountsAccountId;

  /** user that owns the account. null for accounts that are not owned by a user */
  user_id?: UsersUserId | null;

  /** type of account: "free", "basic", "premium"? (TODO: needs to be defined) */
  type?: string | null;

  /** Default value: CURRENT_DATE */
  period_start?: Date | null;

  period_end?: Date | null;

  /** Used to label projects in lists. Either "name" or the name of a key in the data field. Assumed value if is null is "name" */
  projects_label_by?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.accounts
 * Goal: earn money. Separate from users to allow for multiple accounts per user. Enables seeing the account history.
 */
export interface AccountsMutator {
  account_id?: AccountsAccountId;

  /** user that owns the account. null for accounts that are not owned by a user */
  user_id?: UsersUserId | null;

  /** type of account: "free", "basic", "premium"? (TODO: needs to be defined) */
  type?: string | null;

  period_start?: Date | null;

  period_end?: Date | null;

  /** Used to label projects in lists. Either "name" or the name of a key in the data field. Assumed value if is null is "name" */
  projects_label_by?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
