// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the table public.action_report_quantities_history
 * System-versioned history of action_report_quantities. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface ActionReportQuantitiesHistory {
  place_action_report_quantity_id: string;

  account_id: string | null;

  place_action_report_id: string | null;

  unit_id: string | null;

  quantity_integer: number | null;

  quantity_numeric: number | null;

  quantity_text: string | null;

  label: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.action_report_quantities_history
 * System-versioned history of action_report_quantities. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface ActionReportQuantitiesHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  place_action_report_quantity_id?: string;

  account_id?: string | null;

  place_action_report_id?: string | null;

  unit_id?: string | null;

  quantity_integer?: number | null;

  quantity_numeric?: number | null;

  quantity_text?: string | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.action_report_quantities_history
 * System-versioned history of action_report_quantities. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface ActionReportQuantitiesHistoryMutator {
  place_action_report_quantity_id?: string;

  account_id?: string | null;

  place_action_report_id?: string | null;

  unit_id?: string | null;

  quantity_integer?: number | null;

  quantity_numeric?: number | null;

  quantity_text?: string | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
