// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ActionReportsActionReportId } from './ActionReports';
import type { UnitsUnitId } from './Units';

/** Identifier type for public.action_report_quantities */
export type ActionReportQuantitiesActionReportQuantityId = string & { __brand: 'public.action_report_quantities' };

/**
 * Represents the table public.action_report_quantities
 * Quantities of action reports
 */
export default interface ActionReportQuantities {
  action_report_quantity_id: ActionReportQuantitiesActionReportQuantityId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  action_report_id: ActionReportsActionReportId | null;

  unit_id: UnitsUnitId | null;

  /** Used for integer quantities */
  quantity_integer: number | null;

  /** Used for numeric quantities */
  quantity_numeric: number | null;

  /** Used for text quantities */
  quantity_text: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.action_report_quantities
 * Quantities of action reports
 */
export interface ActionReportQuantitiesInitializer {
  /** Default value: uuid_generate_v7() */
  action_report_quantity_id?: ActionReportQuantitiesActionReportQuantityId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  action_report_id?: ActionReportsActionReportId | null;

  unit_id?: UnitsUnitId | null;

  /** Used for integer quantities */
  quantity_integer?: number | null;

  /** Used for numeric quantities */
  quantity_numeric?: number | null;

  /** Used for text quantities */
  quantity_text?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.action_report_quantities
 * Quantities of action reports
 */
export interface ActionReportQuantitiesMutator {
  action_report_quantity_id?: ActionReportQuantitiesActionReportQuantityId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  action_report_id?: ActionReportsActionReportId | null;

  unit_id?: UnitsUnitId | null;

  /** Used for integer quantities */
  quantity_integer?: number | null;

  /** Used for numeric quantities */
  quantity_numeric?: number | null;

  /** Used for text quantities */
  quantity_text?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
