// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ActionsActionId } from './Actions';

/** Identifier type for public.action_reports */
export type ActionReportsActionReportId = string & { __brand: 'public.action_reports' };

/**
 * Represents the table public.action_reports
 * Reporting on the success of actions.
 */
export default interface ActionReports {
  action_report_id: ActionReportsActionReportId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  action_id: ActionsActionId | null;

  /** Year of report. Preset: current year */
  year: number | null;

  /** Room for action report specific data, defined in "fields" table */
  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.action_reports
 * Reporting on the success of actions.
 */
export interface ActionReportsInitializer {
  /** Default value: uuid_generate_v7() */
  action_report_id?: ActionReportsActionReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  action_id?: ActionsActionId | null;

  /**
   * Year of report. Preset: current year
   * Default value: date_part('year'::text, (now())::date)
   */
  year?: number | null;

  /** Room for action report specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.action_reports
 * Reporting on the success of actions.
 */
export interface ActionReportsMutator {
  action_report_id?: ActionReportsActionReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  action_id?: ActionsActionId | null;

  /** Year of report. Preset: current year */
  year?: number | null;

  /** Room for action report specific data, defined in "fields" table */
  data?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
