// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ActionsActionId } from './Actions';
import type { TaxaTaxonId } from './Taxa';
import type { UnitsUnitId } from './Units';

/** Identifier type for public.action_taxa */
export type ActionTaxaActionTaxonId = string & { __brand: 'public.action_taxa' };

/** Represents the table public.action_taxa */
export default interface ActionTaxa {
  action_taxon_id: ActionTaxaActionTaxonId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  action_id: ActionsActionId | null;

  taxon_id: TaxaTaxonId | null;

  unit_id: UnitsUnitId | null;

  quantity_integer: number | null;

  quantity_numeric: number | null;

  quantity_text: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.action_taxa */
export interface ActionTaxaInitializer {
  /** Default value: uuid_generate_v7() */
  action_taxon_id?: ActionTaxaActionTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  action_id?: ActionsActionId | null;

  taxon_id?: TaxaTaxonId | null;

  unit_id?: UnitsUnitId | null;

  quantity_integer?: number | null;

  quantity_numeric?: number | null;

  quantity_text?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.action_taxa */
export interface ActionTaxaMutator {
  action_taxon_id?: ActionTaxaActionTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  action_id?: ActionsActionId | null;

  taxon_id?: TaxaTaxonId | null;

  unit_id?: UnitsUnitId | null;

  quantity_integer?: number | null;

  quantity_numeric?: number | null;

  quantity_text?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
