// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';

/** Identifier type for public.auth_sessions */
export type AuthSessionsAuthSessionId = string & { __brand: 'public.auth_sessions' };

/** Represents the table public.auth_sessions */
export default interface AuthSessions {
  auth_session_id: AuthSessionsAuthSessionId;

  user_id: UsersUserId | null;

  token: string | null;

  expires_at: Date | null;

  ip_address: string | null;

  user_agent: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.auth_sessions */
export interface AuthSessionsInitializer {
  /** Default value: uuid_generate_v7() */
  auth_session_id?: AuthSessionsAuthSessionId;

  user_id?: UsersUserId | null;

  token?: string | null;

  expires_at?: Date | null;

  ip_address?: string | null;

  user_agent?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.auth_sessions */
export interface AuthSessionsMutator {
  auth_session_id?: AuthSessionsAuthSessionId;

  user_id?: UsersUserId | null;

  token?: string | null;

  expires_at?: Date | null;

  ip_address?: string | null;

  user_agent?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
