// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.chart_subject_types */
export type ChartSubjectTypesType = string & { __brand: 'public.chart_subject_types' };

/** Represents the table public.chart_subject_types */
export default interface ChartSubjectTypes {
  type: ChartSubjectTypesType;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.chart_subject_types */
export interface ChartSubjectTypesInitializer {
  type: ChartSubjectTypesType;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.chart_subject_types */
export interface ChartSubjectTypesMutator {
  type?: ChartSubjectTypesType;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
