// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ChartsChartId } from './Charts';
import type { default as ChartSubjectTableNamesEnum } from './ChartSubjectTableNamesEnum';
import type { default as ChartSubjectTableLevelsEnum } from './ChartSubjectTableLevelsEnum';
import type { default as ChartSubjectCalcMethodsEnum } from './ChartSubjectCalcMethodsEnum';
import type { UnitsUnitId } from './Units';
import type { default as ChartSubjectTypesEnum } from './ChartSubjectTypesEnum';

/** Identifier type for public.chart_subjects */
export type ChartSubjectsChartSubjectId = string & { __brand: 'public.chart_subjects' };

/**
 * Represents the table public.chart_subjects
 * Subjects for charts. Or: what is shown in the chart
 */
export default interface ChartSubjects {
  chart_subject_id: ChartSubjectsChartSubjectId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  chart_id: ChartsChartId | null;

  /** The table to be used as data source */
  table_name: ChartSubjectTableNamesEnum | null;

  /** The level of the table to be used as data source. 1 or 2 (not relevant for subprojects) */
  table_level: ChartSubjectTableLevelsEnum | null;

  /** A filter that is applied to the table */
  table_filter: unknown | null;

  /** How to source the value */
  calc_method: ChartSubjectCalcMethodsEnum | null;

  /** Field to be used for calc_method */
  field: string | null;

  /** Needed for action_quantities, check_quantities */
  value_unit: UnitsUnitId | null;

  name: string | null;

  label: string | null;

  type: ChartSubjectTypesEnum | null;

  /** Stroke color of the chart */
  stroke: string | null;

  /** Fill color of the chart */
  fill: string | null;

  fill_graded: boolean | null;

  connect_nulls: boolean | null;

  sort: number | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.chart_subjects
 * Subjects for charts. Or: what is shown in the chart
 */
export interface ChartSubjectsInitializer {
  /** Default value: uuid_generate_v7() */
  chart_subject_id?: ChartSubjectsChartSubjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  chart_id?: ChartsChartId | null;

  /** The table to be used as data source */
  table_name?: ChartSubjectTableNamesEnum | null;

  /**
   * The level of the table to be used as data source. 1 or 2 (not relevant for subprojects)
   * Default value: '1'::chart_subject_table_levels_enum
   */
  table_level?: ChartSubjectTableLevelsEnum | null;

  /** A filter that is applied to the table */
  table_filter?: unknown | null;

  /** How to source the value */
  calc_method?: ChartSubjectCalcMethodsEnum | null;

  /** Field to be used for calc_method */
  field?: string | null;

  /** Needed for action_quantities, check_quantities */
  value_unit?: UnitsUnitId | null;

  name?: string | null;

  label?: string | null;

  type?: ChartSubjectTypesEnum | null;

  /** Stroke color of the chart */
  stroke?: string | null;

  /** Fill color of the chart */
  fill?: string | null;

  /** Default value: true */
  fill_graded?: boolean | null;

  /** Default value: true */
  connect_nulls?: boolean | null;

  /** Default value: 0 */
  sort?: number | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.chart_subjects
 * Subjects for charts. Or: what is shown in the chart
 */
export interface ChartSubjectsMutator {
  chart_subject_id?: ChartSubjectsChartSubjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  chart_id?: ChartsChartId | null;

  /** The table to be used as data source */
  table_name?: ChartSubjectTableNamesEnum | null;

  /** The level of the table to be used as data source. 1 or 2 (not relevant for subprojects) */
  table_level?: ChartSubjectTableLevelsEnum | null;

  /** A filter that is applied to the table */
  table_filter?: unknown | null;

  /** How to source the value */
  calc_method?: ChartSubjectCalcMethodsEnum | null;

  /** Field to be used for calc_method */
  field?: string | null;

  /** Needed for action_quantities, check_quantities */
  value_unit?: UnitsUnitId | null;

  name?: string | null;

  label?: string | null;

  type?: ChartSubjectTypesEnum | null;

  /** Stroke color of the chart */
  stroke?: string | null;

  /** Fill color of the chart */
  fill?: string | null;

  fill_graded?: boolean | null;

  connect_nulls?: boolean | null;

  sort?: number | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
