// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.chart_subject_table_levels_enum */
enum ChartSubjectTableLevelsEnum {
  '1' = '1',
  '2' = '2',
};

export default ChartSubjectTableLevelsEnum;
