// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ChartsChartId } from './Charts';
import type { ChartSubjectTableNamesTableName } from './ChartSubjectTableNames';
import type { ChartSubjectTableLevelsLevel } from './ChartSubjectTableLevels';
import type { ChartSubjectValueSourcesValueSource } from './ChartSubjectValueSources';
import type { UnitsUnitId } from './Units';
import type { ChartSubjectTypesType } from './ChartSubjectTypes';

/** Identifier type for public.chart_subjects */
export type ChartSubjectsChartSubjectId = string & { __brand: 'public.chart_subjects' };

/**
 * Represents the table public.chart_subjects
 * Subjects for charts. Or: what is shown in the chart
 */
export default interface ChartSubjects {
  chart_subject_id: ChartSubjectsChartSubjectId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  chart_id: ChartsChartId | null;

  /** The table to be used as data source */
  table_name: ChartSubjectTableNamesTableName | null;

  /** The level of the table to be used as data source. 1 or 2 (not relevant for subprojects) */
  table_level: ChartSubjectTableLevelsLevel | null;

  /** A filter that is applied to the table */
  table_filter: unknown | null;

  /** How to source the value */
  value_source: ChartSubjectValueSourcesValueSource | null;

  /** Field to be used for value_source */
  value_field: string | null;

  /** Needed for action_values, check_values */
  value_unit: UnitsUnitId | null;

  name: string | null;

  label: string | null;

  type: ChartSubjectTypesType | null;

  /** Stroke color of the chart */
  stroke: string | null;

  /** Fill color of the chart */
  fill: string | null;

  fill_graded: boolean | null;

  connect_nulls: boolean | null;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.chart_subjects
 * Subjects for charts. Or: what is shown in the chart
 */
export interface ChartSubjectsInitializer {
  /** Default value: uuid_generate_v7() */
  chart_subject_id?: ChartSubjectsChartSubjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  chart_id?: ChartsChartId | null;

  /** The table to be used as data source */
  table_name?: ChartSubjectTableNamesTableName | null;

  /**
   * The level of the table to be used as data source. 1 or 2 (not relevant for subprojects)
   * Default value: 1
   */
  table_level?: ChartSubjectTableLevelsLevel | null;

  /** A filter that is applied to the table */
  table_filter?: unknown | null;

  /** How to source the value */
  value_source?: ChartSubjectValueSourcesValueSource | null;

  /** Field to be used for value_source */
  value_field?: string | null;

  /** Needed for action_values, check_values */
  value_unit?: UnitsUnitId | null;

  name?: string | null;

  label?: string | null;

  type?: ChartSubjectTypesType | null;

  /** Stroke color of the chart */
  stroke?: string | null;

  /** Fill color of the chart */
  fill?: string | null;

  /** Default value: true */
  fill_graded?: boolean | null;

  /** Default value: true */
  connect_nulls?: boolean | null;

  /** Default value: 0 */
  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.chart_subjects
 * Subjects for charts. Or: what is shown in the chart
 */
export interface ChartSubjectsMutator {
  chart_subject_id?: ChartSubjectsChartSubjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  chart_id?: ChartsChartId | null;

  /** The table to be used as data source */
  table_name?: ChartSubjectTableNamesTableName | null;

  /** The level of the table to be used as data source. 1 or 2 (not relevant for subprojects) */
  table_level?: ChartSubjectTableLevelsLevel | null;

  /** A filter that is applied to the table */
  table_filter?: unknown | null;

  /** How to source the value */
  value_source?: ChartSubjectValueSourcesValueSource | null;

  /** Field to be used for value_source */
  value_field?: string | null;

  /** Needed for action_values, check_values */
  value_unit?: UnitsUnitId | null;

  name?: string | null;

  label?: string | null;

  type?: ChartSubjectTypesType | null;

  /** Stroke color of the chart */
  stroke?: string | null;

  /** Fill color of the chart */
  fill?: string | null;

  fill_graded?: boolean | null;

  connect_nulls?: boolean | null;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
