// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.chart_subject_table_names */
export type ChartSubjectTableNamesTableName = string & { __brand: 'public.chart_subject_table_names' };

/** Represents the table public.chart_subject_table_names */
export default interface ChartSubjectTableNames {
  table_name: ChartSubjectTableNamesTableName;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.chart_subject_table_names */
export interface ChartSubjectTableNamesInitializer {
  table_name: ChartSubjectTableNamesTableName;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.chart_subject_table_names */
export interface ChartSubjectTableNamesMutator {
  table_name?: ChartSubjectTableNamesTableName;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
