// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.chart_subject_calc_methods_enum */
enum ChartSubjectCalcMethodsEnum {
  count_rows = 'count_rows',
  count_rows_by_distinct_field_values = 'count_rows_by_distinct_field_values',
  sum_values_of_field = 'sum_values_of_field',
};

export default ChartSubjectCalcMethodsEnum;
