// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.chart_subject_table_names_enum */
enum ChartSubjectTableNamesEnum {
  subprojects = 'subprojects',
  places = 'places',
  checks = 'checks',
  check_values = 'check_values',
  actions = 'actions',
  action_values = 'action_values',
};

export default ChartSubjectTableNamesEnum;
