// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';
import type { SubprojectsSubprojectId } from './Subprojects';
import type { PlacesPlaceId } from './Places';
import type { ChartTypesChartType } from './ChartTypes';

/** Identifier type for public.charts */
export type ChartsChartId = string & { __brand: 'public.charts' };

/**
 * Represents the table public.charts
 * Charts for projects, subprojects or places.
 */
export default interface Charts {
  chart_id: ChartsChartId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  subproject_id: SubprojectsSubprojectId | null;

  place_id: PlacesPlaceId | null;

  /** If has value: the chart shows data of the current year */
  years_current: boolean | null;

  /** If has value: the chart shows data of the previous year */
  years_previous: boolean | null;

  /** If has value: the chart shows data of the specific year */
  years_specific: number | null;

  /** If has value: the chart shows data of the last {value} years */
  years_last_x: number | null;

  /** If has value: the chart shows data since the value specified. Can be the start date of the project, subproject or place */
  years_since: number | null;

  /** If has value: the chart shows data until the value specified. Can be the end date of the project, subproject or place */
  years_until: number | null;

  chart_type: ChartTypesChartType | null;

  title: string | null;

  subjects_stacked: boolean | null;

  subjects_single: boolean | null;

  percent: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.charts
 * Charts for projects, subprojects or places.
 */
export interface ChartsInitializer {
  /** Default value: uuid_generate_v7() */
  chart_id?: ChartsChartId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  place_id?: PlacesPlaceId | null;

  /**
   * If has value: the chart shows data of the current year
   * Default value: true
   */
  years_current?: boolean | null;

  /**
   * If has value: the chart shows data of the previous year
   * Default value: false
   */
  years_previous?: boolean | null;

  /** If has value: the chart shows data of the specific year */
  years_specific?: number | null;

  /** If has value: the chart shows data of the last {value} years */
  years_last_x?: number | null;

  /** If has value: the chart shows data since the value specified. Can be the start date of the project, subproject or place */
  years_since?: number | null;

  /** If has value: the chart shows data until the value specified. Can be the end date of the project, subproject or place */
  years_until?: number | null;

  /** Default value: 'Area'::text */
  chart_type?: ChartTypesChartType | null;

  title?: string | null;

  /** Default value: false */
  subjects_stacked?: boolean | null;

  /** Default value: false */
  subjects_single?: boolean | null;

  /** Default value: false */
  percent?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.charts
 * Charts for projects, subprojects or places.
 */
export interface ChartsMutator {
  chart_id?: ChartsChartId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  place_id?: PlacesPlaceId | null;

  /** If has value: the chart shows data of the current year */
  years_current?: boolean | null;

  /** If has value: the chart shows data of the previous year */
  years_previous?: boolean | null;

  /** If has value: the chart shows data of the specific year */
  years_specific?: number | null;

  /** If has value: the chart shows data of the last {value} years */
  years_last_x?: number | null;

  /** If has value: the chart shows data since the value specified. Can be the start date of the project, subproject or place */
  years_since?: number | null;

  /** If has value: the chart shows data until the value specified. Can be the end date of the project, subproject or place */
  years_until?: number | null;

  chart_type?: ChartTypesChartType | null;

  title?: string | null;

  subjects_stacked?: boolean | null;

  subjects_single?: boolean | null;

  percent?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
