// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.chart_types_enum */
enum ChartTypesEnum {
  Pie = 'Pie',
  Radar = 'Radar',
  Area = 'Area',
};

export default ChartTypesEnum;
