// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.chart_subject_calc_methods */
export type ChartSubjectCalcMethodsCalcMethod = string & { __brand: 'public.chart_subject_calc_methods' };

/** Represents the table public.chart_subject_calc_methods */
export default interface ChartSubjectCalcMethods {
  calc_method: ChartSubjectCalcMethodsCalcMethod;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.chart_subject_calc_methods */
export interface ChartSubjectCalcMethodsInitializer {
  calc_method: ChartSubjectCalcMethodsCalcMethod;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.chart_subject_calc_methods */
export interface ChartSubjectCalcMethodsMutator {
  calc_method?: ChartSubjectCalcMethodsCalcMethod;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
