// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.chart_subject_table_levels */
export type ChartSubjectTableLevelsLevel = number & { __brand: 'public.chart_subject_table_levels' };

/** Represents the table public.chart_subject_table_levels */
export default interface ChartSubjectTableLevels {
  level: ChartSubjectTableLevelsLevel;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.chart_subject_table_levels */
export interface ChartSubjectTableLevelsInitializer {
  level: ChartSubjectTableLevelsLevel;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.chart_subject_table_levels */
export interface ChartSubjectTableLevelsMutator {
  level?: ChartSubjectTableLevelsLevel;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
