// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.chart_types */
export type ChartTypesChartType = string & { __brand: 'public.chart_types' };

/** Represents the table public.chart_types */
export default interface ChartTypes {
  chart_type: ChartTypesChartType;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.chart_types */
export interface ChartTypesInitializer {
  chart_type: ChartTypesChartType;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.chart_types */
export interface ChartTypesMutator {
  chart_type?: ChartTypesChartType;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
