// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.chart_subject_value_sources */
export type ChartSubjectValueSourcesValueSource = string & { __brand: 'public.chart_subject_value_sources' };

/** Represents the table public.chart_subject_value_sources */
export default interface ChartSubjectValueSources {
  value_source: ChartSubjectValueSourcesValueSource;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.chart_subject_value_sources */
export interface ChartSubjectValueSourcesInitializer {
  value_source: ChartSubjectValueSourcesValueSource;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.chart_subject_value_sources */
export interface ChartSubjectValueSourcesMutator {
  value_source?: ChartSubjectValueSourcesValueSource;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
