// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.chart_subject_types_enum */
enum ChartSubjectTypesEnum {
  linear = 'linear',
  monotone = 'monotone',
};

export default ChartSubjectTypesEnum;
