// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.chart_subject_table_names_enum */
enum ChartSubjectTableNamesEnum {
  subprojects = 'subprojects',
  places = 'places',
  checks = 'checks',
  check_quantities = 'check_quantities',
  actions = 'actions',
  action_quantities = 'action_quantities',
};

export default ChartSubjectTableNamesEnum;
