// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { CheckReportsCheckReportId } from './CheckReports';
import type { UnitsUnitId } from './Units';

/** Identifier type for public.check_report_quantities */
export type CheckReportQuantitiesCheckReportQuantityId = string & { __brand: 'public.check_report_quantities' };

/**
 * Represents the table public.check_report_quantities
 * Quantities of check reports
 */
export default interface CheckReportQuantities {
  check_report_quantity_id: CheckReportQuantitiesCheckReportQuantityId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  check_report_id: CheckReportsCheckReportId | null;

  unit_id: UnitsUnitId | null;

  /** Used for integer quantities */
  quantity_integer: number | null;

  /** Used for numeric quantities */
  quantity_numeric: number | null;

  /** Used for text quantities */
  quantity_text: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.check_report_quantities
 * Quantities of check reports
 */
export interface CheckReportQuantitiesInitializer {
  /** Default value: uuid_generate_v7() */
  check_report_quantity_id?: CheckReportQuantitiesCheckReportQuantityId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  check_report_id?: CheckReportsCheckReportId | null;

  unit_id?: UnitsUnitId | null;

  /** Used for integer quantities */
  quantity_integer?: number | null;

  /** Used for numeric quantities */
  quantity_numeric?: number | null;

  /** Used for text quantities */
  quantity_text?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.check_report_quantities
 * Quantities of check reports
 */
export interface CheckReportQuantitiesMutator {
  check_report_quantity_id?: CheckReportQuantitiesCheckReportQuantityId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  check_report_id?: CheckReportsCheckReportId | null;

  unit_id?: UnitsUnitId | null;

  /** Used for integer quantities */
  quantity_integer?: number | null;

  /** Used for numeric quantities */
  quantity_numeric?: number | null;

  /** Used for text quantities */
  quantity_text?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
