// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { PlacesPlaceId } from './Places';

/** Identifier type for public.checks */
export type ChecksCheckId = string & { __brand: 'public.checks' };

/**
 * Represents the table public.checks
 * Checks describe the situation of the subproject in this place.
 */
export default interface Checks {
  check_id: ChecksCheckId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  place_id: PlacesPlaceId | null;

  date: Date | null;

  /** Room for check specific data, defined in "fields" table */
  data: unknown | null;

  geometry: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries for viewport client-side */
  bbox: unknown | null;

  relevant_for_reports: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.checks
 * Checks describe the situation of the subproject in this place.
 */
export interface ChecksInitializer {
  /** Default value: uuid_generate_v7() */
  check_id?: ChecksCheckId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  place_id?: PlacesPlaceId | null;

  /** Default value: CURRENT_DATE */
  date?: Date | null;

  /** Room for check specific data, defined in "fields" table */
  data?: unknown | null;

  geometry?: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries for viewport client-side */
  bbox?: unknown | null;

  /** Default value: true */
  relevant_for_reports?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.checks
 * Checks describe the situation of the subproject in this place.
 */
export interface ChecksMutator {
  check_id?: ChecksCheckId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  place_id?: PlacesPlaceId | null;

  date?: Date | null;

  /** Room for check specific data, defined in "fields" table */
  data?: unknown | null;

  geometry?: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries for viewport client-side */
  bbox?: unknown | null;

  relevant_for_reports?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
