// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ChecksCheckId } from './Checks';

/** Identifier type for public.check_reports */
export type CheckReportsCheckReportId = string & { __brand: 'public.check_reports' };

/**
 * Represents the table public.check_reports
 * Reporting on the success of checks.
 */
export default interface CheckReports {
  check_report_id: CheckReportsCheckReportId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  check_id: ChecksCheckId | null;

  /** Year of report. Preset: current year */
  year: number | null;

  /** Room for check report specific data, defined in "fields" table */
  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.check_reports
 * Reporting on the success of checks.
 */
export interface CheckReportsInitializer {
  /** Default value: uuid_generate_v7() */
  check_report_id?: CheckReportsCheckReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  check_id?: ChecksCheckId | null;

  /**
   * Year of report. Preset: current year
   * Default value: date_part('year'::text, (now())::date)
   */
  year?: number | null;

  /** Room for check report specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.check_reports
 * Reporting on the success of checks.
 */
export interface CheckReportsMutator {
  check_report_id?: CheckReportsCheckReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  check_id?: ChecksCheckId | null;

  /** Year of report. Preset: current year */
  year?: number | null;

  /** Room for check report specific data, defined in "fields" table */
  data?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
