// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ChecksCheckId } from './Checks';
import type { TaxaTaxonId } from './Taxa';
import type { UnitsUnitId } from './Units';

/** Identifier type for public.check_taxa */
export type CheckTaxaCheckTaxonId = string & { __brand: 'public.check_taxa' };

/** Represents the table public.check_taxa */
export default interface CheckTaxa {
  check_taxon_id: CheckTaxaCheckTaxonId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  check_id: ChecksCheckId | null;

  taxon_id: TaxaTaxonId | null;

  unit_id: UnitsUnitId | null;

  value_integer: number | null;

  value_numeric: number | null;

  value_text: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.check_taxa */
export interface CheckTaxaInitializer {
  /** Default value: uuid_generate_v7() */
  check_taxon_id?: CheckTaxaCheckTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  check_id?: ChecksCheckId | null;

  taxon_id?: TaxaTaxonId | null;

  unit_id?: UnitsUnitId | null;

  value_integer?: number | null;

  value_numeric?: number | null;

  value_text?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.check_taxa */
export interface CheckTaxaMutator {
  check_taxon_id?: CheckTaxaCheckTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  check_id?: ChecksCheckId | null;

  taxon_id?: TaxaTaxonId | null;

  unit_id?: UnitsUnitId | null;

  value_integer?: number | null;

  value_numeric?: number | null;

  value_text?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
