// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';

/** Identifier type for public.crs */
export type CrsCrsId = string & { __brand: 'public.crs' };

/**
 * Represents the table public.crs
 * List of crs. From: https://spatialreference.org/crslist.json. Can be inserted when configuring a project. We need the entire list because wfs/wms have a default crs that needs to be used for bbox calls. TODO: decide when to download the list.
 */
export default interface Crs {
  crs_id: CrsCrsId;

  account_id: AccountsAccountId | null;

  code: string | null;

  name: string | null;

  /** proj4 string for the crs. From (example): https://epsg.io/4326.proj4 */
  proj4: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.crs
 * List of crs. From: https://spatialreference.org/crslist.json. Can be inserted when configuring a project. We need the entire list because wfs/wms have a default crs that needs to be used for bbox calls. TODO: decide when to download the list.
 */
export interface CrsInitializer {
  /** Default value: uuid_generate_v7() */
  crs_id?: CrsCrsId;

  account_id?: AccountsAccountId | null;

  code?: string | null;

  name?: string | null;

  /** proj4 string for the crs. From (example): https://epsg.io/4326.proj4 */
  proj4?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.crs
 * List of crs. From: https://spatialreference.org/crslist.json. Can be inserted when configuring a project. We need the entire list because wfs/wms have a default crs that needs to be used for bbox calls. TODO: decide when to download the list.
 */
export interface CrsMutator {
  crs_id?: CrsCrsId;

  account_id?: AccountsAccountId | null;

  code?: string | null;

  name?: string | null;

  /** proj4 string for the crs. From (example): https://epsg.io/4326.proj4 */
  proj4?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
