// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.field_types */
export type FieldTypesFieldTypeId = string & { __brand: 'public.field_types' };

/**
 * Represents the table public.field_types
 * Root-level field type definitions. No history tracking needed as these are application-level configuration managed by administrators.
 */
export default interface FieldTypes {
  field_type_id: FieldTypesFieldTypeId;

  name: string | null;

  sort: number | null;

  comment: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;
}

/**
 * Represents the initializer for the table public.field_types
 * Root-level field type definitions. No history tracking needed as these are application-level configuration managed by administrators.
 */
export interface FieldTypesInitializer {
  /** Default value: uuid_generate_v7() */
  field_type_id?: FieldTypesFieldTypeId;

  name?: string | null;

  sort?: number | null;

  comment?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;
}

/**
 * Represents the mutator for the table public.field_types
 * Root-level field type definitions. No history tracking needed as these are application-level configuration managed by administrators.
 */
export interface FieldTypesMutator {
  field_type_id?: FieldTypesFieldTypeId;

  name?: string | null;

  sort?: number | null;

  comment?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period?: string;
}
