// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjectsProjectId } from './Projects';
import type { AccountsAccountId } from './Accounts';
import type { FieldTypesFieldTypeId } from './FieldTypes';
import type { WidgetTypesWidgetTypeId } from './WidgetTypes';
import type { ListsListId } from './Lists';

/** Identifier type for public.fields */
export type FieldsFieldId = string & { __brand: 'public.fields' };

/**
 * Represents the table public.fields
 * Fields are used to define the data structure of data jsonb fields in other tables.
 */
export default interface Fields {
  field_id: FieldsFieldId;

  project_id: ProjectsProjectId | null;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  /** table, on which this field is used inside the jsob field "data" */
  table_name: string | null;

  /** level of field if places or below: 1, 2 */
  level: number | null;

  field_type_id: FieldTypesFieldTypeId | null;

  widget_type_id: WidgetTypesWidgetTypeId | null;

  name: string | null;

  field_label: string | null;

  list_id: ListsListId | null;

  preset: string | null;

  obsolete: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.fields
 * Fields are used to define the data structure of data jsonb fields in other tables.
 */
export interface FieldsInitializer {
  /** Default value: uuid_generate_v7() */
  field_id?: FieldsFieldId;

  project_id?: ProjectsProjectId | null;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  /** table, on which this field is used inside the jsob field "data" */
  table_name?: string | null;

  /**
   * level of field if places or below: 1, 2
   * Default value: 1
   */
  level?: number | null;

  field_type_id?: FieldTypesFieldTypeId | null;

  widget_type_id?: WidgetTypesWidgetTypeId | null;

  name?: string | null;

  field_label?: string | null;

  list_id?: ListsListId | null;

  preset?: string | null;

  /** Default value: false */
  obsolete?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.fields
 * Fields are used to define the data structure of data jsonb fields in other tables.
 */
export interface FieldsMutator {
  field_id?: FieldsFieldId;

  project_id?: ProjectsProjectId | null;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  /** table, on which this field is used inside the jsob field "data" */
  table_name?: string | null;

  /** level of field if places or below: 1, 2 */
  level?: number | null;

  field_type_id?: FieldTypesFieldTypeId | null;

  widget_type_id?: WidgetTypesWidgetTypeId | null;

  name?: string | null;

  field_label?: string | null;

  list_id?: ListsListId | null;

  preset?: string | null;

  obsolete?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
