// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.field_types */
export type FieldTypesFieldTypeId = string & { __brand: 'public.field_types' };

/** Represents the table public.field_types */
export default interface FieldTypes {
  field_type_id: FieldTypesFieldTypeId;

  name: string | null;

  sort: number | null;

  comment: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.field_types */
export interface FieldTypesInitializer {
  /** Default value: uuid_generate_v7() */
  field_type_id?: FieldTypesFieldTypeId;

  name?: string | null;

  sort?: number | null;

  comment?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.field_types */
export interface FieldTypesMutator {
  field_type_id?: FieldTypesFieldTypeId;

  name?: string | null;

  sort?: number | null;

  comment?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
