// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjectsProjectId } from './Projects';
import type { AccountsAccountId } from './Accounts';

/** Identifier type for public.field_sorts */
export type FieldSortsFieldSortId = string & { __brand: 'public.field_sorts' };

/**
 * Represents the table public.field_sorts
 * Stores the sort order of fields per table_name
 */
export default interface FieldSorts {
  field_sort_id: FieldSortsFieldSortId;

  project_id: ProjectsProjectId | null;

  account_id: AccountsAccountId | null;

  table_name: string | null;

  sorted_field_ids: string[] | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.field_sorts
 * Stores the sort order of fields per table_name
 */
export interface FieldSortsInitializer {
  /** Default value: uuid_generate_v7() */
  field_sort_id?: FieldSortsFieldSortId;

  project_id?: ProjectsProjectId | null;

  account_id?: AccountsAccountId | null;

  table_name?: string | null;

  sorted_field_ids?: string[] | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.field_sorts
 * Stores the sort order of fields per table_name
 */
export interface FieldSortsMutator {
  field_sort_id?: FieldSortsFieldSortId;

  project_id?: ProjectsProjectId | null;

  account_id?: AccountsAccountId | null;

  table_name?: string | null;

  sorted_field_ids?: string[] | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
