// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the table public.fields_history
 * System-versioned history of fields. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface FieldsHistory {
  field_id: string;

  project_id: string | null;

  account_id: string | null;

  table_name: string | null;

  level: number | null;

  field_type_id: string | null;

  widget_type_id: string | null;

  name: string | null;

  field_label: string | null;

  list_id: string | null;

  preset: string | null;

  obsolete: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;
}

/**
 * Represents the initializer for the table public.fields_history
 * System-versioned history of fields. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface FieldsHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  field_id?: string;

  project_id?: string | null;

  account_id?: string | null;

  table_name?: string | null;

  /** Default value: 1 */
  level?: number | null;

  field_type_id?: string | null;

  widget_type_id?: string | null;

  name?: string | null;

  field_label?: string | null;

  list_id?: string | null;

  preset?: string | null;

  /** Default value: false */
  obsolete?: boolean | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;
}

/**
 * Represents the mutator for the table public.fields_history
 * System-versioned history of fields. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface FieldsHistoryMutator {
  field_id?: string;

  project_id?: string | null;

  account_id?: string | null;

  table_name?: string | null;

  level?: number | null;

  field_type_id?: string | null;

  widget_type_id?: string | null;

  name?: string | null;

  field_label?: string | null;

  list_id?: string | null;

  preset?: string | null;

  obsolete?: boolean | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;
}
