// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';
import type { SubprojectsSubprojectId } from './Subprojects';
import type { PlacesPlaceId } from './Places';
import type { ActionsActionId } from './Actions';
import type { ChecksCheckId } from './Checks';

/** Identifier type for public.files */
export type FilesFileId = string & { __brand: 'public.files' };

/**
 * Represents the table public.files
 * used to store files.
 */
export default interface Files {
  file_id: FilesFileId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  subproject_id: SubprojectsSubprojectId | null;

  place_id: PlacesPlaceId | null;

  action_id: ActionsActionId | null;

  check_id: ChecksCheckId | null;

  name: string | null;

  size: string | null;

  label: string | null;

  /** Room for file specific data, defined in "fields" table */
  data: unknown | null;

  /** mimetype of file, used to know how to open or preview it */
  mimetype: string | null;

  width: number | null;

  height: number | null;

  /** file content */
  file: unknown | null;

  preview: unknown | null;

  /** URL of file, if it is saved on a web service */
  url: string | null;

  uuid: string | null;

  preview_uuid: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.files
 * used to store files.
 */
export interface FilesInitializer {
  /** Default value: uuid_generate_v7() */
  file_id?: FilesFileId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  place_id?: PlacesPlaceId | null;

  action_id?: ActionsActionId | null;

  check_id?: ChecksCheckId | null;

  name?: string | null;

  size?: string | null;

  /** Room for file specific data, defined in "fields" table */
  data?: unknown | null;

  /** mimetype of file, used to know how to open or preview it */
  mimetype?: string | null;

  width?: number | null;

  height?: number | null;

  /** file content */
  file?: unknown | null;

  preview?: unknown | null;

  /** URL of file, if it is saved on a web service */
  url?: string | null;

  uuid?: string | null;

  preview_uuid?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.files
 * used to store files.
 */
export interface FilesMutator {
  file_id?: FilesFileId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  place_id?: PlacesPlaceId | null;

  action_id?: ActionsActionId | null;

  check_id?: ChecksCheckId | null;

  name?: string | null;

  size?: string | null;

  /** Room for file specific data, defined in "fields" table */
  data?: unknown | null;

  /** mimetype of file, used to know how to open or preview it */
  mimetype?: string | null;

  width?: number | null;

  height?: number | null;

  /** file content */
  file?: unknown | null;

  preview?: unknown | null;

  /** URL of file, if it is saved on a web service */
  url?: string | null;

  uuid?: string | null;

  preview_uuid?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
