// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { GoalsGoalId } from './Goals';

/** Identifier type for public.goal_reports */
export type GoalReportsGoalReportId = string & { __brand: 'public.goal_reports' };

/**
 * Represents the table public.goal_reports
 * Reporting on the success of goals.
 */
export default interface GoalReports {
  goal_report_id: GoalReportsGoalReportId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  goal_id: GoalsGoalId | null;

  /** Room for goal report specific data, defined in "fields" table */
  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.goal_reports
 * Reporting on the success of goals.
 */
export interface GoalReportsInitializer {
  /** Default value: uuid_generate_v7() */
  goal_report_id?: GoalReportsGoalReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  goal_id?: GoalsGoalId | null;

  /** Room for goal report specific data, defined in "fields" table */
  data?: unknown | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.goal_reports
 * Reporting on the success of goals.
 */
export interface GoalReportsMutator {
  goal_report_id?: GoalReportsGoalReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  goal_id?: GoalsGoalId | null;

  /** Room for goal report specific data, defined in "fields" table */
  data?: unknown | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
