// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface immutabletaxonomytype_params {
  $1: unknown;
}

/** Return type for immutabletaxonomytype */
export type immutabletaxonomytype_return_type = string;
