// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface immutabledate_params {
  $1: Date;
}

/** Return type for immutabledate */
export type immutabledate_return_type = string;
