// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface immutabletimestamptz_params {
  $1: unknown;
}

/** Return type for immutabletimestamptz */
export type immutabletimestamptz_return_type = string;
