// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { WmsLayersWmsLayerId } from './WmsLayers';
import type { VectorLayersVectorLayerId } from './VectorLayers';

/** Identifier type for public.layer_presentations */
export type LayerPresentationsLayerPresentationId = string & { __brand: 'public.layer_presentations' };

/**
 * Represents the table public.layer_presentations
 * Goal: manage all presentation related properties of all layers (including wms and vector layers). Editable by all users.
 */
export default interface LayerPresentations {
  layer_presentation_id: LayerPresentationsLayerPresentationId;

  account_id: AccountsAccountId | null;

  wms_layer_id: WmsLayersWmsLayerId | null;

  vector_layer_id: VectorLayersVectorLayerId | null;

  active: boolean | null;

  /** As numeric is not supported by electric-sql, we cant use values between 0 and 1 for opacity. So we use integer values between 0 and 100 and divide by 100 in the frontend. */
  opacity_percent: number | null;

  transparent: boolean | null;

  grayscale: boolean | null;

  max_zoom: number | null;

  min_zoom: number | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.layer_presentations
 * Goal: manage all presentation related properties of all layers (including wms and vector layers). Editable by all users.
 */
export interface LayerPresentationsInitializer {
  /** Default value: uuid_generate_v7() */
  layer_presentation_id?: LayerPresentationsLayerPresentationId;

  account_id?: AccountsAccountId | null;

  wms_layer_id?: WmsLayersWmsLayerId | null;

  vector_layer_id?: VectorLayersVectorLayerId | null;

  /** Default value: false */
  active?: boolean | null;

  /**
   * As numeric is not supported by electric-sql, we cant use values between 0 and 1 for opacity. So we use integer values between 0 and 100 and divide by 100 in the frontend.
   * Default value: 100
   */
  opacity_percent?: number | null;

  /** Default value: false */
  transparent?: boolean | null;

  /** Default value: false */
  grayscale?: boolean | null;

  /** Default value: 19 */
  max_zoom?: number | null;

  /** Default value: 0 */
  min_zoom?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.layer_presentations
 * Goal: manage all presentation related properties of all layers (including wms and vector layers). Editable by all users.
 */
export interface LayerPresentationsMutator {
  layer_presentation_id?: LayerPresentationsLayerPresentationId;

  account_id?: AccountsAccountId | null;

  wms_layer_id?: WmsLayersWmsLayerId | null;

  vector_layer_id?: VectorLayersVectorLayerId | null;

  active?: boolean | null;

  /** As numeric is not supported by electric-sql, we cant use values between 0 and 1 for opacity. So we use integer values between 0 and 100 and divide by 100 in the frontend. */
  opacity_percent?: number | null;

  transparent?: boolean | null;

  grayscale?: boolean | null;

  max_zoom?: number | null;

  min_zoom?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
