// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ListsListId } from './Lists';

/** Identifier type for public.list_values */
export type ListValuesListValueId = string & { __brand: 'public.list_values' };

/** Represents the table public.list_values */
export default interface ListValues {
  list_value_id: ListValuesListValueId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  list_id: ListsListId | null;

  /** Value of list, like "Gefährdet", "5". If is a number, will have to be coerced to number when used. */
  value: string | null;

  obsolete: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.list_values */
export interface ListValuesInitializer {
  /** Default value: uuid_generate_v7() */
  list_value_id?: ListValuesListValueId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  list_id?: ListsListId | null;

  /** Value of list, like "Gefährdet", "5". If is a number, will have to be coerced to number when used. */
  value?: string | null;

  /** Default value: false */
  obsolete?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.list_values */
export interface ListValuesMutator {
  list_value_id?: ListValuesListValueId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  list_id?: ListsListId | null;

  /** Value of list, like "Gefährdet", "5". If is a number, will have to be coerced to number when used. */
  value?: string | null;

  obsolete?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
