// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.list_value_types_enum */
enum ListValueTypesEnum {
  integer = 'integer',
  numeric = 'numeric',
  text = 'text',
  date = 'date',
  datetime = 'datetime',
};

export default ListValueTypesEnum;
