// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';

/** Identifier type for public.lists */
export type ListsListId = string & { __brand: 'public.lists' };

/**
 * Represents the table public.lists
 * Manage lists of values. These lists can then be used on option-lists or dropdown-lists
 */
export default interface Lists {
  list_id: ListsListId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  /** Name of list, like "Gefährdung" */
  name: string | null;

  data: unknown | null;

  /** Is list obsolete? If so, show set values but dont let user pick one. Preset: false */
  obsolete: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.lists
 * Manage lists of values. These lists can then be used on option-lists or dropdown-lists
 */
export interface ListsInitializer {
  /** Default value: uuid_generate_v7() */
  list_id?: ListsListId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** Name of list, like "Gefährdung" */
  name?: string | null;

  data?: unknown | null;

  /**
   * Is list obsolete? If so, show set values but dont let user pick one. Preset: false
   * Default value: false
   */
  obsolete?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.lists
 * Manage lists of values. These lists can then be used on option-lists or dropdown-lists
 */
export interface ListsMutator {
  list_id?: ListsListId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** Name of list, like "Gefährdung" */
  name?: string | null;

  data?: unknown | null;

  /** Is list obsolete? If so, show set values but dont let user pick one. Preset: false */
  obsolete?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
