// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.list_value_types */
export type ListValueTypesType = string & { __brand: 'public.list_value_types' };

/** Represents the table public.list_value_types */
export default interface ListValueTypes {
  type: ListValueTypesType;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.list_value_types */
export interface ListValueTypesInitializer {
  type: ListValueTypesType;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.list_value_types */
export interface ListValueTypesMutator {
  type?: ListValueTypesType;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
