// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the table public.messages_history
 * System-versioned history of messages. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface MessagesHistory {
  message_id: string;

  date: Date | null;

  message: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.messages_history
 * System-versioned history of messages. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface MessagesHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  message_id?: string;

  /** Default value: now() */
  date?: Date | null;

  message?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.messages_history
 * System-versioned history of messages. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface MessagesHistoryMutator {
  message_id?: string;

  date?: Date | null;

  message?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
