// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.messages */
export type MessagesMessageId = string & { __brand: 'public.messages' };

/**
 * Represents the table public.messages
 * System messages for users. No history tracking needed as these are transient notifications managed by the system.
 */
export default interface Messages {
  message_id: MessagesMessageId;

  date: Date | null;

  message: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;
}

/**
 * Represents the initializer for the table public.messages
 * System messages for users. No history tracking needed as these are transient notifications managed by the system.
 */
export interface MessagesInitializer {
  /** Default value: uuid_generate_v7() */
  message_id?: MessagesMessageId;

  /** Default value: now() */
  date?: Date | null;

  message?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;
}

/**
 * Represents the mutator for the table public.messages
 * System messages for users. No history tracking needed as these are transient notifications managed by the system.
 */
export interface MessagesMutator {
  message_id?: MessagesMessageId;

  date?: Date | null;

  message?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period?: string;
}
