// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.observation_imports_geometry_methods */
export type ObservationImportsGeometryMethodsGeometryMethod = string & { __brand: 'public.observation_imports_geometry_methods' };

/** Represents the table public.observation_imports_geometry_methods */
export default interface ObservationImportsGeometryMethods {
  geometry_method: ObservationImportsGeometryMethodsGeometryMethod;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.observation_imports_geometry_methods */
export interface ObservationImportsGeometryMethodsInitializer {
  geometry_method: ObservationImportsGeometryMethodsGeometryMethod;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.observation_imports_geometry_methods */
export interface ObservationImportsGeometryMethodsMutator {
  geometry_method?: ObservationImportsGeometryMethodsGeometryMethod;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
