// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.observation_imports_geometry_methods_enum */
enum ObservationImportsGeometryMethodsEnum {
  coordinates = 'coordinates',
  geojson = 'geojson',
};

export default ObservationImportsGeometryMethodsEnum;
