// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';
import type { OccurrenceImportsGeometryMethodsGeometryMethod } from './OccurrenceImportsGeometryMethods';

/** Identifier type for public.occurrence_imports */
export type OccurrenceImportsOccurrenceImportId = string & { __brand: 'public.occurrence_imports' };

/**
 * Represents the table public.occurrence_imports
 * occurrence imports. Used also for species (when from gbif, of an area, format: SPECIES_LIST). Is created in client, synced to server, executed by gbif backend server, written to db and synced back to client
 */
export default interface OccurrenceImports {
  occurrence_import_id: OccurrenceImportsOccurrenceImportId;

  account_id: AccountsAccountId | null;

  subproject_id: SubprojectsSubprojectId | null;

  created_time: Date | null;

  inserted_count: number | null;

  id_field: string | null;

  geometry_method: OccurrenceImportsGeometryMethodsGeometryMethod | null;

  geojson_geometry_field: string | null;

  x_coordinate_field: string | null;

  y_coordinate_field: string | null;

  crs: string | null;

  label_creation: unknown | null;

  name: string | null;

  attribution: string | null;

  /** What import does this one update/replace/extend? */
  previous_import: OccurrenceImportsOccurrenceImportId | null;

  download_from_gbif: boolean | null;

  /** area, groups, speciesKeys... */
  gbif_filters: unknown | null;

  gbif_download_key: string | null;

  gbif_error: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.occurrence_imports
 * occurrence imports. Used also for species (when from gbif, of an area, format: SPECIES_LIST). Is created in client, synced to server, executed by gbif backend server, written to db and synced back to client
 */
export interface OccurrenceImportsInitializer {
  /** Default value: uuid_generate_v7() */
  occurrence_import_id?: OccurrenceImportsOccurrenceImportId;

  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /** Default value: now() */
  created_time?: Date | null;

  inserted_count?: number | null;

  id_field?: string | null;

  geometry_method?: OccurrenceImportsGeometryMethodsGeometryMethod | null;

  geojson_geometry_field?: string | null;

  x_coordinate_field?: string | null;

  y_coordinate_field?: string | null;

  /** Default value: 4326 */
  crs?: string | null;

  label_creation?: unknown | null;

  name?: string | null;

  attribution?: string | null;

  /** What import does this one update/replace/extend? */
  previous_import?: OccurrenceImportsOccurrenceImportId | null;

  download_from_gbif?: boolean | null;

  /** area, groups, speciesKeys... */
  gbif_filters?: unknown | null;

  gbif_download_key?: string | null;

  gbif_error?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.occurrence_imports
 * occurrence imports. Used also for species (when from gbif, of an area, format: SPECIES_LIST). Is created in client, synced to server, executed by gbif backend server, written to db and synced back to client
 */
export interface OccurrenceImportsMutator {
  occurrence_import_id?: OccurrenceImportsOccurrenceImportId;

  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  created_time?: Date | null;

  inserted_count?: number | null;

  id_field?: string | null;

  geometry_method?: OccurrenceImportsGeometryMethodsGeometryMethod | null;

  geojson_geometry_field?: string | null;

  x_coordinate_field?: string | null;

  y_coordinate_field?: string | null;

  crs?: string | null;

  label_creation?: unknown | null;

  name?: string | null;

  attribution?: string | null;

  /** What import does this one update/replace/extend? */
  previous_import?: OccurrenceImportsOccurrenceImportId | null;

  download_from_gbif?: boolean | null;

  /** area, groups, speciesKeys... */
  gbif_filters?: unknown | null;

  gbif_download_key?: string | null;

  gbif_error?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
