// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.occurrence_import_previous_operations */
export type OccurrenceImportPreviousOperationsPreviousImportOperation = string & { __brand: 'public.occurrence_import_previous_operations' };

/** Represents the table public.occurrence_import_previous_operations */
export default interface OccurrenceImportPreviousOperations {
  previous_import_operation: OccurrenceImportPreviousOperationsPreviousImportOperation;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.occurrence_import_previous_operations */
export interface OccurrenceImportPreviousOperationsInitializer {
  previous_import_operation: OccurrenceImportPreviousOperationsPreviousImportOperation;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.occurrence_import_previous_operations */
export interface OccurrenceImportPreviousOperationsMutator {
  previous_import_operation?: OccurrenceImportPreviousOperationsPreviousImportOperation;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
