// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.occurrence_imports_geometry_methods */
export type OccurrenceImportsGeometryMethodsGeometryMethod = string & { __brand: 'public.occurrence_imports_geometry_methods' };

/** Represents the table public.occurrence_imports_geometry_methods */
export default interface OccurrenceImportsGeometryMethods {
  geometry_method: OccurrenceImportsGeometryMethodsGeometryMethod;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.occurrence_imports_geometry_methods */
export interface OccurrenceImportsGeometryMethodsInitializer {
  geometry_method: OccurrenceImportsGeometryMethodsGeometryMethod;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.occurrence_imports_geometry_methods */
export interface OccurrenceImportsGeometryMethodsMutator {
  geometry_method?: OccurrenceImportsGeometryMethodsGeometryMethod;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
