// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjectsProjectId } from './Projects';
import type { AccountsAccountId } from './Accounts';

/** Identifier type for public.persons */
export type PersonsPersonId = string & { __brand: 'public.persons' };

/**
 * Represents the table public.persons
 * Persons are used to assign actions and checks to
 */
export default interface Persons {
  person_id: PersonsPersonId;

  project_id: ProjectsProjectId | null;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  email: string | null;

  /** Room for person specific data, defined in "fields" table */
  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.persons
 * Persons are used to assign actions and checks to
 */
export interface PersonsInitializer {
  /** Default value: uuid_generate_v7() */
  person_id?: PersonsPersonId;

  project_id?: ProjectsProjectId | null;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  email?: string | null;

  /** Room for person specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.persons
 * Persons are used to assign actions and checks to
 */
export interface PersonsMutator {
  person_id?: PersonsPersonId;

  project_id?: ProjectsProjectId | null;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  email?: string | null;

  /** Room for person specific data, defined in "fields" table */
  data?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
