// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts'
import type { ProjectsProjectId } from './Projects'

/** Identifier type for public.place_levels */
export type PlaceLevelsPlaceLevelId = string & {
  __brand: 'public.place_levels'
}

/**
 * Represents the table public.place_levels
 * Goal: manage place levels. Enable working with one or two levels. Organize what features are used on which level.
 */
export default interface PlaceLevels {
  place_level_id: PlaceLevelsPlaceLevelId

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null

  project_id: ProjectsProjectId | null

  /** level of place: 1, 2 */
  level: number | null

  /** German singular name. Preset: "Population" */
  name_singular_de: string | null

  /** German plural name. Preset: "Populationen" */
  name_plural_de: string | null

  /** English singular name. Preset: "Population" */
  name_singular_en: string | null

  /** English plural name. Preset: "Populations" */
  name_plural_en: string | null

  /** French singular name. Preset: "Population" */
  name_singular_fr: string | null

  /** French plural name. Preset: "Populations" */
  name_plural_fr: string | null

  /** Italian singular name. Preset: "Popolazione" */
  name_singular_it: string | null

  /** Italian plural name. Preset: "Popolazioni" */
  name_plural_it: string | null

  /** Are check reports for places used? Preset: true */
  place_check_reports: boolean | null

  /** Are place check report quantities used? Preset: true */
  place_check_report_quantities: boolean | null

  /** Show place check report quantities inside the report form instead of a separate route? Preset: true */
  place_check_report_quantities_in_report: boolean | null

  /** Are action reports for places used? Preset: true */
  place_action_reports: boolean | null

  /** Are place action report quantities used? Preset: true */
  place_action_report_quantities: boolean | null

  /** Show place action report quantities inside the report form instead of a separate route? Preset: true */
  place_action_report_quantities_in_report: boolean | null

  /** Are actions used? Preset: true */
  actions: boolean | null

  /** Are action values used? Preset: true */
  action_quantities: boolean | null

  action_quantities_in_action: boolean | null

  action_taxa: boolean | null

  action_taxa_in_action: boolean | null

  /** Are checks used? Preset: true */
  checks: boolean | null

  /** Are check values used? Preset: true */
  check_quantities: boolean | null

  /** Show check quantities inside the check form instead of a separate route? Preset: true */
  check_quantities_in_check: boolean | null

  /** Are check taxa used? Preset: true */
  check_taxa: boolean | null

  check_taxa_in_check: boolean | null

  /** Are observations used? Preset: true */
  observations: boolean | null

  /** Are files used for places on this level? Preset: false */
  place_files: boolean | null

  /** Are files used for actions on this level? Preset: false */
  action_files: boolean | null

  /** Are files used for checks on this level? Preset: false */
  check_files: boolean | null

  /** Render files inside the check form? Preset: true */
  files_in_check: boolean | null

  label: string | null

  created_at: Date

  updated_at: Date

  updated_by: string | null
}

/**
 * Represents the initializer for the table public.place_levels
 * Goal: manage place levels. Enable working with one or two levels. Organize what features are used on which level.
 */
export interface PlaceLevelsInitializer {
  /** Default value: uuid_generate_v7() */
  place_level_id?: PlaceLevelsPlaceLevelId

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null

  project_id?: ProjectsProjectId | null

  /**
   * level of place: 1, 2
   * Default value: 1
   */
  level?: number | null

  /** German singular name. Preset: "Population" */
  name_singular_de?: string | null

  /** German plural name. Preset: "Populationen" */
  name_plural_de?: string | null

  /** English singular name. Preset: "Population" */
  name_singular_en?: string | null

  /** English plural name. Preset: "Populations" */
  name_plural_en?: string | null

  /** French singular name. Preset: "Population" */
  name_singular_fr?: string | null

  /** French plural name. Preset: "Populations" */
  name_plural_fr?: string | null

  /** Italian singular name. Preset: "Popolazione" */
  name_singular_it?: string | null

  /** Italian plural name. Preset: "Popolazioni" */
  name_plural_it?: string | null

  /**
   * Are check reports for places used? Preset: true
   * Default value: true
   */
  place_check_reports?: boolean | null

  /**
   * Are place check report quantities used? Preset: true
   * Default value: true
   */
  place_check_report_quantities?: boolean | null

  /**
   * Show place check report quantities inside the report form instead of a separate route? Preset: true
   * Default value: true
   */
  place_check_report_quantities_in_report?: boolean | null

  /**
   * Are action reports for places used? Preset: true
   * Default value: true
   */
  place_action_reports?: boolean | null

  /**
   * Are place action report quantities used? Preset: true
   * Default value: true
   */
  place_action_report_quantities?: boolean | null

  /**
   * Show place action report quantities inside the report form instead of a separate route? Preset: true
   * Default value: true
   */
  place_action_report_quantities_in_report?: boolean | null

  /**
   * Are actions used? Preset: true
   * Default value: true
   */
  actions?: boolean | null

  /**
   * Are action values used? Preset: true
   * Default value: true
   */
  action_quantities?: boolean | null

  /** Default value: true */
  action_quantities_in_action?: boolean | null

  /** Default value: true */
  action_taxa?: boolean | null

  /** Default value: true */
  action_taxa_in_action?: boolean | null

  /**
   * Are checks used? Preset: true
   * Default value: true
   */
  checks?: boolean | null

  /**
   * Are check values used? Preset: true
   * Default value: true
   */
  check_quantities?: boolean | null

  /**
   * Show check quantities inside the check form instead of a separate route? Preset: true
   * Default value: true
   */
  check_quantities_in_check?: boolean | null

  /**
   * Are check taxa used? Preset: true
   * Default value: true
   */
  check_taxa?: boolean | null

  /** Default value: true */
  check_taxa_in_check?: boolean | null

  /**
   * Are observations used? Preset: true
   * Default value: true
   */
  observations?: boolean | null

  /**
   * Are files used for places on this level? Preset: false
   * Default value: true
   */
  place_files?: boolean | null

  /**
   * Are files used for actions on this level? Preset: false
   * Default value: true
   */
  action_files?: boolean | null

  /**
   * Are files used for checks on this level? Preset: false
   * Default value: true
   */
  check_files?: boolean | null

  /**
   * Render files inside the check form? Preset: true
   * Default value: true
   */
  files_in_check?: boolean | null

  /** Default value: now() */
  created_at?: Date

  /** Default value: now() */
  updated_at?: Date

  updated_by?: string | null
}

/**
 * Represents the mutator for the table public.place_levels
 * Goal: manage place levels. Enable working with one or two levels. Organize what features are used on which level.
 */
export interface PlaceLevelsMutator {
  place_level_id?: PlaceLevelsPlaceLevelId

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null

  project_id?: ProjectsProjectId | null

  /** level of place: 1, 2 */
  level?: number | null

  /** German singular name. Preset: "Population" */
  name_singular_de?: string | null

  /** German plural name. Preset: "Populationen" */
  name_plural_de?: string | null

  /** English singular name. Preset: "Population" */
  name_singular_en?: string | null

  /** English plural name. Preset: "Populations" */
  name_plural_en?: string | null

  /** French singular name. Preset: "Population" */
  name_singular_fr?: string | null

  /** French plural name. Preset: "Populations" */
  name_plural_fr?: string | null

  /** Italian singular name. Preset: "Popolazione" */
  name_singular_it?: string | null

  /** Italian plural name. Preset: "Popolazioni" */
  name_plural_it?: string | null

  /** Are check reports for places used? Preset: true */
  place_check_reports?: boolean | null

  /** Are place check report quantities used? Preset: true */
  place_check_report_quantities?: boolean | null

  /** Show place check report quantities inside the report form instead of a separate route? Preset: true */
  place_check_report_quantities_in_report?: boolean | null

  /** Are action reports for places used? Preset: true */
  place_action_reports?: boolean | null

  /** Are place action report quantities used? Preset: true */
  place_action_report_quantities?: boolean | null

  /** Show place action report quantities inside the report form instead of a separate route? Preset: true */
  place_action_report_quantities_in_report?: boolean | null

  /** Are actions used? Preset: true */
  actions?: boolean | null

  /** Are action values used? Preset: true */
  action_quantities?: boolean | null

  action_quantities_in_action?: boolean | null

  action_taxa?: boolean | null

  action_taxa_in_action?: boolean | null

  /** Are checks used? Preset: true */
  checks?: boolean | null

  /** Are check values used? Preset: true */
  check_quantities?: boolean | null

  /** Show check quantities inside the check form instead of a separate route? Preset: true */
  check_quantities_in_check?: boolean | null

  /** Are check taxa used? Preset: true */
  check_taxa?: boolean | null

  check_taxa_in_check?: boolean | null

  /** Are observations used? Preset: true */
  observations?: boolean | null

  /** Are files used for places on this level? Preset: false */
  place_files?: boolean | null

  /** Are files used for actions on this level? Preset: false */
  action_files?: boolean | null

  /** Are files used for checks on this level? Preset: false */
  check_files?: boolean | null

  /** Render files inside the check form? Preset: true */
  files_in_check?: boolean | null

  created_at?: Date

  updated_at?: Date

  updated_by?: string | null
}
