// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { PlacesPlaceId } from './Places';

/** Identifier type for public.place_reports */
export type PlaceReportsPlaceReportId = string & { __brand: 'public.place_reports' };

/**
 * Represents the table public.place_reports
 * Reporting on the situation of the subproject in this place.
 */
export default interface PlaceReports {
  place_report_id: PlaceReportsPlaceReportId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  place_id: PlacesPlaceId | null;

  /** Year of report. Preset: current year */
  year: number | null;

  /** Room for place report specific data, defined in "fields" table */
  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.place_reports
 * Reporting on the situation of the subproject in this place.
 */
export interface PlaceReportsInitializer {
  /** Default value: uuid_generate_v7() */
  place_report_id?: PlaceReportsPlaceReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  place_id?: PlacesPlaceId | null;

  /**
   * Year of report. Preset: current year
   * Default value: date_part('year'::text, (now())::date)
   */
  year?: number | null;

  /** Room for place report specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.place_reports
 * Reporting on the situation of the subproject in this place.
 */
export interface PlaceReportsMutator {
  place_report_id?: PlaceReportsPlaceReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  place_id?: PlacesPlaceId | null;

  /** Year of report. Preset: current year */
  year?: number | null;

  /** Room for place report specific data, defined in "fields" table */
  data?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
