// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';

/** Identifier type for public.places */
export type PlacesPlaceId = string & { __brand: 'public.places' };

/**
 * Represents the table public.places
 * Places are where actions and checks are done. They can be organized in a hierarchy of one or two levels.
 */
export default interface Places {
  place_id: PlacesPlaceId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  /** always set to optimize queries */
  subproject_id: SubprojectsSubprojectId | null;

  /** parent place. null for places of level 1 */
  parent_id: PlacesPlaceId | null;

  /** level of place: 1, 2 */
  level: number | null;

  /** start year of place */
  since: number | null;

  /** end year of place */
  until: number | null;

  /** Room for place specific data, defined in "fields" table */
  data: unknown | null;

  /** geometry of place */
  geometry: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries for viewport client-side */
  bbox: unknown | null;

  label: string | null;

  files_active_places: boolean | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.places
 * Places are where actions and checks are done. They can be organized in a hierarchy of one or two levels.
 */
export interface PlacesInitializer {
  /** Default value: uuid_generate_v7() */
  place_id?: PlacesPlaceId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  /** always set to optimize queries */
  subproject_id?: SubprojectsSubprojectId | null;

  /** parent place. null for places of level 1 */
  parent_id?: PlacesPlaceId | null;

  /**
   * level of place: 1, 2
   * Default value: 1
   */
  level?: number | null;

  /** start year of place */
  since?: number | null;

  /** end year of place */
  until?: number | null;

  /** Room for place specific data, defined in "fields" table */
  data?: unknown | null;

  /** geometry of place */
  geometry?: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries for viewport client-side */
  bbox?: unknown | null;

  label?: string | null;

  /** Default value: true */
  files_active_places?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.places
 * Places are where actions and checks are done. They can be organized in a hierarchy of one or two levels.
 */
export interface PlacesMutator {
  place_id?: PlacesPlaceId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  /** always set to optimize queries */
  subproject_id?: SubprojectsSubprojectId | null;

  /** parent place. null for places of level 1 */
  parent_id?: PlacesPlaceId | null;

  /** level of place: 1, 2 */
  level?: number | null;

  /** start year of place */
  since?: number | null;

  /** end year of place */
  until?: number | null;

  /** Room for place specific data, defined in "fields" table */
  data?: unknown | null;

  /** geometry of place */
  geometry?: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries for viewport client-side */
  bbox?: unknown | null;

  label?: string | null;

  files_active_places?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
