// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the table public.place_levels_history
 * System-versioned history of place_levels. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface PlaceLevelsHistory {
  place_level_id: string;

  account_id: string | null;

  project_id: string | null;

  level: number | null;

  name_singular_de: string | null;

  name_plural_de: string | null;

  name_singular_en: string | null;

  name_plural_en: string | null;

  name_singular_fr: string | null;

  name_plural_fr: string | null;

  name_singular_it: string | null;

  name_plural_it: string | null;

  check_reports: boolean | null;

  check_report_quantities: boolean | null;

  check_report_quantities_in_report: boolean | null;

  place_action_reports: boolean | null;

  place_action_report_quantities: boolean | null;

  place_action_report_quantities_in_report: boolean | null;

  actions: boolean | null;

  action_quantities: boolean | null;

  action_quantities_in_action: boolean | null;

  action_taxa: boolean | null;

  action_taxa_in_action: boolean | null;

  checks: boolean | null;

  check_quantities: boolean | null;

  check_quantities_in_check: boolean | null;

  check_taxa: boolean | null;

  check_taxa_in_check: boolean | null;

  observations: boolean | null;

  place_files: boolean | null;

  place_files_in_place: boolean | null;

  action_files: boolean | null;

  action_files_in_action: boolean | null;

  check_files: boolean | null;

  check_files_in_check: boolean | null;

  label: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.place_levels_history
 * System-versioned history of place_levels. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface PlaceLevelsHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  place_level_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  /** Default value: 1 */
  level?: number | null;

  name_singular_de?: string | null;

  name_plural_de?: string | null;

  name_singular_en?: string | null;

  name_plural_en?: string | null;

  name_singular_fr?: string | null;

  name_plural_fr?: string | null;

  name_singular_it?: string | null;

  name_plural_it?: string | null;

  /** Default value: true */
  check_reports?: boolean | null;

  /** Default value: true */
  check_report_quantities?: boolean | null;

  /** Default value: true */
  check_report_quantities_in_report?: boolean | null;

  /** Default value: true */
  place_action_reports?: boolean | null;

  /** Default value: true */
  place_action_report_quantities?: boolean | null;

  /** Default value: true */
  place_action_report_quantities_in_report?: boolean | null;

  /** Default value: true */
  actions?: boolean | null;

  /** Default value: true */
  action_quantities?: boolean | null;

  /** Default value: true */
  action_quantities_in_action?: boolean | null;

  /** Default value: true */
  action_taxa?: boolean | null;

  /** Default value: true */
  action_taxa_in_action?: boolean | null;

  /** Default value: true */
  checks?: boolean | null;

  /** Default value: true */
  check_quantities?: boolean | null;

  /** Default value: true */
  check_quantities_in_check?: boolean | null;

  /** Default value: true */
  check_taxa?: boolean | null;

  /** Default value: true */
  check_taxa_in_check?: boolean | null;

  /** Default value: true */
  observations?: boolean | null;

  /** Default value: true */
  place_files?: boolean | null;

  /** Default value: true */
  place_files_in_place?: boolean | null;

  /** Default value: true */
  action_files?: boolean | null;

  /** Default value: true */
  action_files_in_action?: boolean | null;

  /** Default value: true */
  check_files?: boolean | null;

  /** Default value: true */
  check_files_in_check?: boolean | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.place_levels_history
 * System-versioned history of place_levels. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface PlaceLevelsHistoryMutator {
  place_level_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  level?: number | null;

  name_singular_de?: string | null;

  name_plural_de?: string | null;

  name_singular_en?: string | null;

  name_plural_en?: string | null;

  name_singular_fr?: string | null;

  name_plural_fr?: string | null;

  name_singular_it?: string | null;

  name_plural_it?: string | null;

  check_reports?: boolean | null;

  check_report_quantities?: boolean | null;

  check_report_quantities_in_report?: boolean | null;

  place_action_reports?: boolean | null;

  place_action_report_quantities?: boolean | null;

  place_action_report_quantities_in_report?: boolean | null;

  actions?: boolean | null;

  action_quantities?: boolean | null;

  action_quantities_in_action?: boolean | null;

  action_taxa?: boolean | null;

  action_taxa_in_action?: boolean | null;

  checks?: boolean | null;

  check_quantities?: boolean | null;

  check_quantities_in_check?: boolean | null;

  check_taxa?: boolean | null;

  check_taxa_in_check?: boolean | null;

  observations?: boolean | null;

  place_files?: boolean | null;

  place_files_in_place?: boolean | null;

  action_files?: boolean | null;

  action_files_in_action?: boolean | null;

  check_files?: boolean | null;

  check_files_in_check?: boolean | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
