// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PlacesPlaceId } from './Places';
import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';

/** Identifier type for public.place_histories */
export type PlaceHistoriesPlaceHistoryId = string & { __brand: 'public.place_histories' };

/**
 * Represents the table public.place_histories
 * History of places. Used to analyze place development over the years.
 */
export default interface PlaceHistories {
  place_history_id: PlaceHistoriesPlaceHistoryId;

  place_id: PlacesPlaceId | null;

  /** One history entry per year per place */
  year: number | null;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  subproject_id: SubprojectsSubprojectId | null;

  parent_id: PlacesPlaceId | null;

  level: number | null;

  since: number | null;

  until: number | null;

  data: unknown | null;

  geometry: unknown | null;

  bbox: unknown | null;

  label: string | null;

  files_active_places: boolean | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.place_histories
 * History of places. Used to analyze place development over the years.
 */
export interface PlaceHistoriesInitializer {
  /** Default value: uuid_generate_v7() */
  place_history_id?: PlaceHistoriesPlaceHistoryId;

  place_id?: PlacesPlaceId | null;

  /** One history entry per year per place */
  year?: number | null;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  parent_id?: PlacesPlaceId | null;

  /** Default value: 1 */
  level?: number | null;

  since?: number | null;

  until?: number | null;

  data?: unknown | null;

  geometry?: unknown | null;

  bbox?: unknown | null;

  label?: string | null;

  /** Default value: true */
  files_active_places?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.place_histories
 * History of places. Used to analyze place development over the years.
 */
export interface PlaceHistoriesMutator {
  place_history_id?: PlaceHistoriesPlaceHistoryId;

  place_id?: PlacesPlaceId | null;

  /** One history entry per year per place */
  year?: number | null;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  parent_id?: PlacesPlaceId | null;

  level?: number | null;

  since?: number | null;

  until?: number | null;

  data?: unknown | null;

  geometry?: unknown | null;

  bbox?: unknown | null;

  label?: string | null;

  files_active_places?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
