// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { PlacesPlaceId } from './Places';
import type { UsersUserId } from './Users';
import type { UserRolesRole } from './UserRoles';

/** Identifier type for public.place_users */
export type PlaceUsersPlaceUserId = string & { __brand: 'public.place_users' };

/**
 * Represents the table public.place_users
 * A way to give users access to places without giving them access to the whole project or subproject.
 */
export default interface PlaceUsers {
  place_user_id: PlaceUsersPlaceUserId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  place_id: PlacesPlaceId | null;

  user_id: UsersUserId | null;

  /** One of: "manager", "editor", "reader". Preset: "reader" */
  role: UserRolesRole | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.place_users
 * A way to give users access to places without giving them access to the whole project or subproject.
 */
export interface PlaceUsersInitializer {
  /** Default value: uuid_generate_v7() */
  place_user_id?: PlaceUsersPlaceUserId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  place_id?: PlacesPlaceId | null;

  user_id?: UsersUserId | null;

  /**
   * One of: "manager", "editor", "reader". Preset: "reader"
   * Default value: 'reader'::text
   */
  role?: UserRolesRole | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.place_users
 * A way to give users access to places without giving them access to the whole project or subproject.
 */
export interface PlaceUsersMutator {
  place_user_id?: PlaceUsersPlaceUserId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  place_id?: PlacesPlaceId | null;

  user_id?: UsersUserId | null;

  /** One of: "manager", "editor", "reader". Preset: "reader" */
  role?: UserRolesRole | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
