// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';

/** Identifier type for public.place_levels */
export type PlaceLevelsPlaceLevelId = string & { __brand: 'public.place_levels' };

/**
 * Represents the table public.place_levels
 * Goal: manage place levels. Enable working with one or two levels. Organize what features are used on which level.
 */
export default interface PlaceLevels {
  place_level_id: PlaceLevelsPlaceLevelId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  /** level of place: 1, 2 */
  level: number | null;

  /** German singular name. Preset: "Population" */
  name_singular_de: string | null;

  /** German plural name. Preset: "Populationen" */
  name_plural_de: string | null;

  /** German short name. Preset: "Pop" */
  name_short_de: string | null;

  /** English singular name. Preset: "Population" */
  name_singular_en: string | null;

  /** English plural name. Preset: "Populations" */
  name_plural_en: string | null;

  /** English short name. Preset: "Pop" */
  name_short_en: string | null;

  /** French singular name. Preset: "Population" */
  name_singular_fr: string | null;

  /** French plural name. Preset: "Populations" */
  name_plural_fr: string | null;

  /** French short name. Preset: "Pop" */
  name_short_fr: string | null;

  /** Italian singular name. Preset: "Popolazione" */
  name_singular_it: string | null;

  /** Italian plural name. Preset: "Popolazioni" */
  name_plural_it: string | null;

  /** Italian short name. Preset: "Pop" */
  name_short_it: string | null;

  /** Are reports used? Preset: true */
  reports: boolean | null;

  /** Are report values used? Preset: true */
  report_values: boolean | null;

  /** Are actions used? Preset: true */
  actions: boolean | null;

  /** Are action values used? Preset: true */
  action_values: boolean | null;

  /** Are action reports used? Preset: true */
  action_reports: boolean | null;

  /** Are checks used? Preset: true */
  checks: boolean | null;

  /** Are check values used? Preset: true */
  check_values: boolean | null;

  /** Are check taxa used? Preset: true */
  check_taxa: boolean | null;

  /** Are observations used? Preset: true */
  observations: boolean | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.place_levels
 * Goal: manage place levels. Enable working with one or two levels. Organize what features are used on which level.
 */
export interface PlaceLevelsInitializer {
  /** Default value: uuid_generate_v7() */
  place_level_id?: PlaceLevelsPlaceLevelId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /**
   * level of place: 1, 2
   * Default value: 1
   */
  level?: number | null;

  /** German singular name. Preset: "Population" */
  name_singular_de?: string | null;

  /** German plural name. Preset: "Populationen" */
  name_plural_de?: string | null;

  /** German short name. Preset: "Pop" */
  name_short_de?: string | null;

  /** English singular name. Preset: "Population" */
  name_singular_en?: string | null;

  /** English plural name. Preset: "Populations" */
  name_plural_en?: string | null;

  /** English short name. Preset: "Pop" */
  name_short_en?: string | null;

  /** French singular name. Preset: "Population" */
  name_singular_fr?: string | null;

  /** French plural name. Preset: "Populations" */
  name_plural_fr?: string | null;

  /** French short name. Preset: "Pop" */
  name_short_fr?: string | null;

  /** Italian singular name. Preset: "Popolazione" */
  name_singular_it?: string | null;

  /** Italian plural name. Preset: "Popolazioni" */
  name_plural_it?: string | null;

  /** Italian short name. Preset: "Pop" */
  name_short_it?: string | null;

  /**
   * Are reports used? Preset: true
   * Default value: false
   */
  reports?: boolean | null;

  /**
   * Are report values used? Preset: true
   * Default value: false
   */
  report_values?: boolean | null;

  /**
   * Are actions used? Preset: true
   * Default value: false
   */
  actions?: boolean | null;

  /**
   * Are action values used? Preset: true
   * Default value: false
   */
  action_values?: boolean | null;

  /**
   * Are action reports used? Preset: true
   * Default value: false
   */
  action_reports?: boolean | null;

  /**
   * Are checks used? Preset: true
   * Default value: false
   */
  checks?: boolean | null;

  /**
   * Are check values used? Preset: true
   * Default value: false
   */
  check_values?: boolean | null;

  /**
   * Are check taxa used? Preset: true
   * Default value: false
   */
  check_taxa?: boolean | null;

  /**
   * Are observations used? Preset: true
   * Default value: false
   */
  observations?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.place_levels
 * Goal: manage place levels. Enable working with one or two levels. Organize what features are used on which level.
 */
export interface PlaceLevelsMutator {
  place_level_id?: PlaceLevelsPlaceLevelId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** level of place: 1, 2 */
  level?: number | null;

  /** German singular name. Preset: "Population" */
  name_singular_de?: string | null;

  /** German plural name. Preset: "Populationen" */
  name_plural_de?: string | null;

  /** German short name. Preset: "Pop" */
  name_short_de?: string | null;

  /** English singular name. Preset: "Population" */
  name_singular_en?: string | null;

  /** English plural name. Preset: "Populations" */
  name_plural_en?: string | null;

  /** English short name. Preset: "Pop" */
  name_short_en?: string | null;

  /** French singular name. Preset: "Population" */
  name_singular_fr?: string | null;

  /** French plural name. Preset: "Populations" */
  name_plural_fr?: string | null;

  /** French short name. Preset: "Pop" */
  name_short_fr?: string | null;

  /** Italian singular name. Preset: "Popolazione" */
  name_singular_it?: string | null;

  /** Italian plural name. Preset: "Popolazioni" */
  name_plural_it?: string | null;

  /** Italian short name. Preset: "Pop" */
  name_short_it?: string | null;

  /** Are reports used? Preset: true */
  reports?: boolean | null;

  /** Are report values used? Preset: true */
  report_values?: boolean | null;

  /** Are actions used? Preset: true */
  actions?: boolean | null;

  /** Are action values used? Preset: true */
  action_values?: boolean | null;

  /** Are action reports used? Preset: true */
  action_reports?: boolean | null;

  /** Are checks used? Preset: true */
  checks?: boolean | null;

  /** Are check values used? Preset: true */
  check_values?: boolean | null;

  /** Are check taxa used? Preset: true */
  check_taxa?: boolean | null;

  /** Are observations used? Preset: true */
  observations?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
