// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectTypesType } from './ProjectTypes';

/** Identifier type for public.projects */
export type ProjectsProjectId = string & { __brand: 'public.projects' };

/**
 * Represents the table public.projects
 * Goal: manage projects
 */
export default interface Projects {
  project_id: ProjectsProjectId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  name: string | null;

  label: string | null;

  /** "species" or "biotope", preset: "species" */
  type: ProjectTypesType | null;

  /** Preset: "Art" */
  subproject_name_singular: string | null;

  /** Preset: "Arten" */
  subproject_name_plural: string | null;

  subproject_order_by: string | null;

  /** Used to label places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added in sqlite and postgresql. */
  places_label_by: string | null;

  /** Used to order places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added and indexed in sqlite and postgresql. */
  places_order_by: string | null;

  persons_label_by: string | null;

  persons_order_by: string | null;

  goals_label_by: string | null;

  goal_reports_label_by: string | null;

  goal_reports_order_by: string | null;

  /** One of: "use first", "use second", "use all". Preset: "use first" */
  values_on_multiple_levels: string | null;

  /** One of: "use all", "use last". Preset: "use all" */
  multiple_action_values_on_same_level: string | null;

  /** One of: "use all", "use last". Preset: "use last" */
  multiple_check_values_on_same_level: string | null;

  /** Room for project specific data, defined in "fields" table */
  data: unknown | null;

  files_offline: boolean | null;

  /** Whether files are used in table projects. Preset: true */
  files_active_projects: boolean | null;

  /** Whether files are used in table subprojects. Preset: true */
  files_active_subprojects: boolean | null;

  /** Whether files are used in table places. Preset: true */
  files_active_places: boolean | null;

  /** Whether files are used in table actions. Preset: true */
  files_active_actions: boolean | null;

  /** Whether files are used in table checks. Preset: true */
  files_active_checks: boolean | null;

  /** Coordinate Reference System for presentation of map. Preset: "EPSG:4326" */
  map_presentation_crs: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.projects
 * Goal: manage projects
 */
export interface ProjectsInitializer {
  /** Default value: uuid_generate_v7() */
  project_id?: ProjectsProjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  name?: string | null;

  label?: string | null;

  /** "species" or "biotope", preset: "species" */
  type?: ProjectTypesType | null;

  /** Preset: "Art" */
  subproject_name_singular?: string | null;

  /** Preset: "Arten" */
  subproject_name_plural?: string | null;

  subproject_order_by?: string | null;

  /** Used to label places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added in sqlite and postgresql. */
  places_label_by?: string | null;

  /** Used to order places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added and indexed in sqlite and postgresql. */
  places_order_by?: string | null;

  persons_label_by?: string | null;

  persons_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  /** One of: "use first", "use second", "use all". Preset: "use first" */
  values_on_multiple_levels?: string | null;

  /** One of: "use all", "use last". Preset: "use all" */
  multiple_action_values_on_same_level?: string | null;

  /** One of: "use all", "use last". Preset: "use last" */
  multiple_check_values_on_same_level?: string | null;

  /** Room for project specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: false */
  files_offline?: boolean | null;

  /**
   * Whether files are used in table projects. Preset: true
   * Default value: true
   */
  files_active_projects?: boolean | null;

  /**
   * Whether files are used in table subprojects. Preset: true
   * Default value: true
   */
  files_active_subprojects?: boolean | null;

  /**
   * Whether files are used in table places. Preset: true
   * Default value: true
   */
  files_active_places?: boolean | null;

  /**
   * Whether files are used in table actions. Preset: true
   * Default value: true
   */
  files_active_actions?: boolean | null;

  /**
   * Whether files are used in table checks. Preset: true
   * Default value: true
   */
  files_active_checks?: boolean | null;

  /** Coordinate Reference System for presentation of map. Preset: "EPSG:4326" */
  map_presentation_crs?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.projects
 * Goal: manage projects
 */
export interface ProjectsMutator {
  project_id?: ProjectsProjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  name?: string | null;

  label?: string | null;

  /** "species" or "biotope", preset: "species" */
  type?: ProjectTypesType | null;

  /** Preset: "Art" */
  subproject_name_singular?: string | null;

  /** Preset: "Arten" */
  subproject_name_plural?: string | null;

  subproject_order_by?: string | null;

  /** Used to label places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added in sqlite and postgresql. */
  places_label_by?: string | null;

  /** Used to order places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added and indexed in sqlite and postgresql. */
  places_order_by?: string | null;

  persons_label_by?: string | null;

  persons_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  /** One of: "use first", "use second", "use all". Preset: "use first" */
  values_on_multiple_levels?: string | null;

  /** One of: "use all", "use last". Preset: "use all" */
  multiple_action_values_on_same_level?: string | null;

  /** One of: "use all", "use last". Preset: "use last" */
  multiple_check_values_on_same_level?: string | null;

  /** Room for project specific data, defined in "fields" table */
  data?: unknown | null;

  files_offline?: boolean | null;

  /** Whether files are used in table projects. Preset: true */
  files_active_projects?: boolean | null;

  /** Whether files are used in table subprojects. Preset: true */
  files_active_subprojects?: boolean | null;

  /** Whether files are used in table places. Preset: true */
  files_active_places?: boolean | null;

  /** Whether files are used in table actions. Preset: true */
  files_active_actions?: boolean | null;

  /** Whether files are used in table checks. Preset: true */
  files_active_checks?: boolean | null;

  /** Coordinate Reference System for presentation of map. Preset: "EPSG:4326" */
  map_presentation_crs?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
