// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';

/** Identifier type for public.project_report_subdesigns */
export type ProjectReportSubdesignsProjectReportSubdesignId = string & { __brand: 'public.project_report_subdesigns' };

/**
 * Represents the table public.project_report_subdesigns
 * Customizable subdesigns for project reports, stored as JSON.
 */
export default interface ProjectReportSubdesigns {
  project_report_subdesign_id: ProjectReportSubdesignsProjectReportSubdesignId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  name: string | null;

  /** JSON design of the project report subdesign. */
  design: unknown | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.project_report_subdesigns
 * Customizable subdesigns for project reports, stored as JSON.
 */
export interface ProjectReportSubdesignsInitializer {
  /** Default value: uuid_generate_v7() */
  project_report_subdesign_id?: ProjectReportSubdesignsProjectReportSubdesignId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  name?: string | null;

  /** JSON design of the project report subdesign. */
  design?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.project_report_subdesigns
 * Customizable subdesigns for project reports, stored as JSON.
 */
export interface ProjectReportSubdesignsMutator {
  project_report_subdesign_id?: ProjectReportSubdesignsProjectReportSubdesignId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  name?: string | null;

  /** JSON design of the project report subdesign. */
  design?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
