// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { default as ProjectTypesEnum } from './ProjectTypesEnum';
import type { UnitsUnitId } from './Units';

/** Identifier type for public.projects */
export type ProjectsProjectId = string & { __brand: 'public.projects' };

/**
 * Represents the table public.projects
 * Goal: manage projects
 */
export default interface Projects {
  project_id: ProjectsProjectId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  name: string | null;

  label: string | null;

  /** "species" or "biotope", preset: "species" */
  type: ProjectTypesEnum | null;

  /** Preset: "Art" */
  subproject_name_singular: string | null;

  /** Preset: "Arten" */
  subproject_name_plural: string | null;

  subproject_name_singular_en: string | null;

  subproject_name_plural_en: string | null;

  subproject_name_singular_fr: string | null;

  subproject_name_plural_fr: string | null;

  subproject_name_singular_it: string | null;

  subproject_name_plural_it: string | null;

  subproject_order_by: string | null;

  /** Used to label places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added in sqlite and postgresql. */
  places_label_by: string | null;

  /** Used to order places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added and indexed in sqlite and postgresql. */
  places_order_by: string | null;

  goals_label_by: string | null;

  goal_reports_label_by: string | null;

  goal_reports_order_by: string | null;

  /** Default unit for action values. */
  actions_default_unit_id: UnitsUnitId | null;

  /** Default unit for check values. Can be overwritten in checks */
  checks_default_unit_id: UnitsUnitId | null;

  /** Default unit for check taxa values. Can be overwritten in check_taxa */
  check_taxa_default_unit_id: UnitsUnitId | null;

  /** Default unit for action taxa values. Can be overwritten in action_taxa */
  action_taxa_default_unit_id: UnitsUnitId | null;

  /** Default unit for place check report quantities. Can be overwritten in check_reports */
  check_reports_default_unit_id: UnitsUnitId | null;

  /** Default unit for place action report quantities. Can be overwritten in action_reports */
  action_reports_default_unit_id: UnitsUnitId | null;

  /** One of: "use first", "use second", "use all". Preset: "use first" */
  values_on_multiple_levels: string | null;

  /** One of: "use all", "use last". Preset: "use all" */
  multiple_action_quantities_on_same_level: string | null;

  /** One of: "use all", "use last". Preset: "use last" */
  multiple_check_quantities_on_same_level: string | null;

  /** Whether wms-services and wms-layers are shown. Preset: false. */
  wms_layers: boolean | null;

  /** Whether vector-layers and wfs-services are shown. Preset: false. */
  vector_layers: boolean | null;

  /** Whether project-reports are shown. Preset: true. */
  project_reports: boolean | null;

  /** Whether subproject-reports are shown. Preset: true. */
  subproject_reports: boolean | null;

  /** Whether goals (subproject) are shown. Preset: true. */
  goals: boolean | null;

  /** Whether occurrences (observation imports, to assess, not to assign) are shown. Preset: true. */
  occurrences: boolean | null;

  /** Whether subproject taxa are shown. Preset: true. */
  taxa: boolean | null;

  /** Whether charts (subproject) are shown. Preset: true. */
  charts: boolean | null;

  /** Whether history comparison is enabled for places. Preset: true. */
  enable_histories: boolean | null;

  /** Room for project specific data, defined in "fields" table */
  data: unknown | null;

  files_offline: boolean | null;

  /** Whether files are used in table projects. Preset: true */
  files_active_projects: boolean | null;

  /** Render files inside the project form? Preset: true */
  project_files_in_project: boolean | null;

  /** Whether files are used in table subprojects. Preset: true */
  files_active_subprojects: boolean | null;

  /** Render files inside the subproject form? Preset: true */
  subproject_files_in_subproject: boolean | null;

  /** Coordinate Reference System for presentation of map. Preset: "EPSG:4326" */
  map_presentation_crs: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.projects
 * Goal: manage projects
 */
export interface ProjectsInitializer {
  /** Default value: uuid_generate_v7() */
  project_id?: ProjectsProjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  name?: string | null;

  label?: string | null;

  /**
   * "species" or "biotope", preset: "species"
   * Default value: 'species'::project_types_enum
   */
  type?: ProjectTypesEnum | null;

  /** Preset: "Art" */
  subproject_name_singular?: string | null;

  /** Preset: "Arten" */
  subproject_name_plural?: string | null;

  subproject_name_singular_en?: string | null;

  subproject_name_plural_en?: string | null;

  subproject_name_singular_fr?: string | null;

  subproject_name_plural_fr?: string | null;

  subproject_name_singular_it?: string | null;

  subproject_name_plural_it?: string | null;

  subproject_order_by?: string | null;

  /** Used to label places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added in sqlite and postgresql. */
  places_label_by?: string | null;

  /** Used to order places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added and indexed in sqlite and postgresql. */
  places_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  /** Default unit for action values. */
  actions_default_unit_id?: UnitsUnitId | null;

  /** Default unit for check values. Can be overwritten in checks */
  checks_default_unit_id?: UnitsUnitId | null;

  /** Default unit for check taxa values. Can be overwritten in check_taxa */
  check_taxa_default_unit_id?: UnitsUnitId | null;

  /** Default unit for action taxa values. Can be overwritten in action_taxa */
  action_taxa_default_unit_id?: UnitsUnitId | null;

  /** Default unit for place check report quantities. Can be overwritten in check_reports */
  check_reports_default_unit_id?: UnitsUnitId | null;

  /** Default unit for place action report quantities. Can be overwritten in action_reports */
  action_reports_default_unit_id?: UnitsUnitId | null;

  /** One of: "use first", "use second", "use all". Preset: "use first" */
  values_on_multiple_levels?: string | null;

  /** One of: "use all", "use last". Preset: "use all" */
  multiple_action_quantities_on_same_level?: string | null;

  /** One of: "use all", "use last". Preset: "use last" */
  multiple_check_quantities_on_same_level?: string | null;

  /**
   * Whether wms-services and wms-layers are shown. Preset: false.
   * Default value: true
   */
  wms_layers?: boolean | null;

  /**
   * Whether vector-layers and wfs-services are shown. Preset: false.
   * Default value: true
   */
  vector_layers?: boolean | null;

  /**
   * Whether project-reports are shown. Preset: true.
   * Default value: true
   */
  project_reports?: boolean | null;

  /**
   * Whether subproject-reports are shown. Preset: true.
   * Default value: true
   */
  subproject_reports?: boolean | null;

  /**
   * Whether goals (subproject) are shown. Preset: true.
   * Default value: true
   */
  goals?: boolean | null;

  /**
   * Whether occurrences (observation imports, to assess, not to assign) are shown. Preset: true.
   * Default value: true
   */
  occurrences?: boolean | null;

  /**
   * Whether subproject taxa are shown. Preset: true.
   * Default value: true
   */
  taxa?: boolean | null;

  /**
   * Whether charts (subproject) are shown. Preset: true.
   * Default value: true
   */
  charts?: boolean | null;

  /**
   * Whether history comparison is enabled for places. Preset: true.
   * Default value: true
   */
  enable_histories?: boolean | null;

  /** Room for project specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: false */
  files_offline?: boolean | null;

  /**
   * Whether files are used in table projects. Preset: true
   * Default value: true
   */
  files_active_projects?: boolean | null;

  /**
   * Render files inside the project form? Preset: true
   * Default value: true
   */
  project_files_in_project?: boolean | null;

  /**
   * Whether files are used in table subprojects. Preset: true
   * Default value: true
   */
  files_active_subprojects?: boolean | null;

  /**
   * Render files inside the subproject form? Preset: true
   * Default value: true
   */
  subproject_files_in_subproject?: boolean | null;

  /** Coordinate Reference System for presentation of map. Preset: "EPSG:4326" */
  map_presentation_crs?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.projects
 * Goal: manage projects
 */
export interface ProjectsMutator {
  project_id?: ProjectsProjectId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  name?: string | null;

  label?: string | null;

  /** "species" or "biotope", preset: "species" */
  type?: ProjectTypesEnum | null;

  /** Preset: "Art" */
  subproject_name_singular?: string | null;

  /** Preset: "Arten" */
  subproject_name_plural?: string | null;

  subproject_name_singular_en?: string | null;

  subproject_name_plural_en?: string | null;

  subproject_name_singular_fr?: string | null;

  subproject_name_plural_fr?: string | null;

  subproject_name_singular_it?: string | null;

  subproject_name_plural_it?: string | null;

  subproject_order_by?: string | null;

  /** Used to label places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added in sqlite and postgresql. */
  places_label_by?: string | null;

  /** Used to order places in lists. Contains an array of names of fields included in the data field (first priority) or table itself. TODO: One or multiple comma separated virtual fields will be added and indexed in sqlite and postgresql. */
  places_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  /** Default unit for action values. */
  actions_default_unit_id?: UnitsUnitId | null;

  /** Default unit for check values. Can be overwritten in checks */
  checks_default_unit_id?: UnitsUnitId | null;

  /** Default unit for check taxa values. Can be overwritten in check_taxa */
  check_taxa_default_unit_id?: UnitsUnitId | null;

  /** Default unit for action taxa values. Can be overwritten in action_taxa */
  action_taxa_default_unit_id?: UnitsUnitId | null;

  /** Default unit for place check report quantities. Can be overwritten in check_reports */
  check_reports_default_unit_id?: UnitsUnitId | null;

  /** Default unit for place action report quantities. Can be overwritten in action_reports */
  action_reports_default_unit_id?: UnitsUnitId | null;

  /** One of: "use first", "use second", "use all". Preset: "use first" */
  values_on_multiple_levels?: string | null;

  /** One of: "use all", "use last". Preset: "use all" */
  multiple_action_quantities_on_same_level?: string | null;

  /** One of: "use all", "use last". Preset: "use last" */
  multiple_check_quantities_on_same_level?: string | null;

  /** Whether wms-services and wms-layers are shown. Preset: false. */
  wms_layers?: boolean | null;

  /** Whether vector-layers and wfs-services are shown. Preset: false. */
  vector_layers?: boolean | null;

  /** Whether project-reports are shown. Preset: true. */
  project_reports?: boolean | null;

  /** Whether subproject-reports are shown. Preset: true. */
  subproject_reports?: boolean | null;

  /** Whether goals (subproject) are shown. Preset: true. */
  goals?: boolean | null;

  /** Whether occurrences (observation imports, to assess, not to assign) are shown. Preset: true. */
  occurrences?: boolean | null;

  /** Whether subproject taxa are shown. Preset: true. */
  taxa?: boolean | null;

  /** Whether charts (subproject) are shown. Preset: true. */
  charts?: boolean | null;

  /** Whether history comparison is enabled for places. Preset: true. */
  enable_histories?: boolean | null;

  /** Room for project specific data, defined in "fields" table */
  data?: unknown | null;

  files_offline?: boolean | null;

  /** Whether files are used in table projects. Preset: true */
  files_active_projects?: boolean | null;

  /** Render files inside the project form? Preset: true */
  project_files_in_project?: boolean | null;

  /** Whether files are used in table subprojects. Preset: true */
  files_active_subprojects?: boolean | null;

  /** Render files inside the subproject form? Preset: true */
  subproject_files_in_subproject?: boolean | null;

  /** Coordinate Reference System for presentation of map. Preset: "EPSG:4326" */
  map_presentation_crs?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
