// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.project_types */
export type ProjectTypesType = string & { __brand: 'public.project_types' };

/** Represents the table public.project_types */
export default interface ProjectTypes {
  type: ProjectTypesType;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.project_types */
export interface ProjectTypesInitializer {
  type: ProjectTypesType;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.project_types */
export interface ProjectTypesMutator {
  type?: ProjectTypesType;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
