// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';
import type { UsersUserId } from './Users';
import type { UserRolesRole } from './UserRoles';

/** Identifier type for public.project_users */
export type ProjectUsersProjectUserId = string & { __brand: 'public.project_users' };

/**
 * Represents the table public.project_users
 * A way to give users access to projects (without giving them access to the whole account).
 */
export default interface ProjectUsers {
  project_user_id: ProjectUsersProjectUserId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  user_id: UsersUserId | null;

  /** TODO: One of: "manager", "editor", "reader". Preset: "reader" */
  role: UserRolesRole | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.project_users
 * A way to give users access to projects (without giving them access to the whole account).
 */
export interface ProjectUsersInitializer {
  /** Default value: uuid_generate_v7() */
  project_user_id?: ProjectUsersProjectUserId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  user_id?: UsersUserId | null;

  /** TODO: One of: "manager", "editor", "reader". Preset: "reader" */
  role?: UserRolesRole | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.project_users
 * A way to give users access to projects (without giving them access to the whole account).
 */
export interface ProjectUsersMutator {
  project_user_id?: ProjectUsersProjectUserId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  user_id?: UsersUserId | null;

  /** TODO: One of: "manager", "editor", "reader". Preset: "reader" */
  role?: UserRolesRole | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
