// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserRolesEnum } from './UserRolesEnum';

/**
 * Represents the table public.project_users_history
 * System-versioned history of project_users. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface ProjectUsersHistory {
  project_user_id: string;

  account_id: string | null;

  project_id: string | null;

  user_id: string | null;

  role: UserRolesEnum | null;

  label: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.project_users_history
 * System-versioned history of project_users. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface ProjectUsersHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  project_user_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  user_id?: string | null;

  role?: UserRolesEnum | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.project_users_history
 * System-versioned history of project_users. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface ProjectUsersHistoryMutator {
  project_user_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  user_id?: string | null;

  role?: UserRolesEnum | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
