// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as ProjectTypesEnum } from './ProjectTypesEnum';

/**
 * Represents the table public.projects_history
 * System-versioned history of projects. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface ProjectsHistory {
  project_id: string;

  account_id: string | null;

  name: string | null;

  label: string | null;

  type: ProjectTypesEnum | null;

  subproject_name_singular: string | null;

  subproject_name_plural: string | null;

  subproject_name_singular_en: string | null;

  subproject_name_plural_en: string | null;

  subproject_name_singular_fr: string | null;

  subproject_name_plural_fr: string | null;

  subproject_name_singular_it: string | null;

  subproject_name_plural_it: string | null;

  subproject_order_by: string | null;

  places_label_by: string | null;

  places_order_by: string | null;

  goals_label_by: string | null;

  goal_reports_label_by: string | null;

  goal_reports_order_by: string | null;

  actions_default_unit_id: string | null;

  checks_default_unit_id: string | null;

  check_taxa_default_unit_id: string | null;

  action_taxa_default_unit_id: string | null;

  check_reports_default_unit_id: string | null;

  action_reports_default_unit_id: string | null;

  values_on_multiple_levels: string | null;

  multiple_action_quantities_on_same_level: string | null;

  multiple_check_quantities_on_same_level: string | null;

  wms_layers: boolean | null;

  vector_layers: boolean | null;

  project_reports: boolean | null;

  subproject_reports: boolean | null;

  goals: boolean | null;

  occurrences: boolean | null;

  taxa: boolean | null;

  charts: boolean | null;

  enable_histories: boolean | null;

  data: unknown | null;

  files_offline: boolean | null;

  files_active_projects: boolean | null;

  project_files_in_project: boolean | null;

  files_active_subprojects: boolean | null;

  subproject_files_in_subproject: boolean | null;

  map_presentation_crs: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.projects_history
 * System-versioned history of projects. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface ProjectsHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  project_id?: string;

  account_id?: string | null;

  name?: string | null;

  label?: string | null;

  /** Default value: 'species'::project_types_enum */
  type?: ProjectTypesEnum | null;

  subproject_name_singular?: string | null;

  subproject_name_plural?: string | null;

  subproject_name_singular_en?: string | null;

  subproject_name_plural_en?: string | null;

  subproject_name_singular_fr?: string | null;

  subproject_name_plural_fr?: string | null;

  subproject_name_singular_it?: string | null;

  subproject_name_plural_it?: string | null;

  subproject_order_by?: string | null;

  places_label_by?: string | null;

  places_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  actions_default_unit_id?: string | null;

  checks_default_unit_id?: string | null;

  check_taxa_default_unit_id?: string | null;

  action_taxa_default_unit_id?: string | null;

  check_reports_default_unit_id?: string | null;

  action_reports_default_unit_id?: string | null;

  values_on_multiple_levels?: string | null;

  multiple_action_quantities_on_same_level?: string | null;

  multiple_check_quantities_on_same_level?: string | null;

  /** Default value: true */
  wms_layers?: boolean | null;

  /** Default value: true */
  vector_layers?: boolean | null;

  /** Default value: true */
  project_reports?: boolean | null;

  /** Default value: true */
  subproject_reports?: boolean | null;

  /** Default value: true */
  goals?: boolean | null;

  /** Default value: true */
  occurrences?: boolean | null;

  /** Default value: true */
  taxa?: boolean | null;

  /** Default value: true */
  charts?: boolean | null;

  /** Default value: true */
  enable_histories?: boolean | null;

  data?: unknown | null;

  /** Default value: false */
  files_offline?: boolean | null;

  /** Default value: true */
  files_active_projects?: boolean | null;

  /** Default value: true */
  project_files_in_project?: boolean | null;

  /** Default value: true */
  files_active_subprojects?: boolean | null;

  /** Default value: true */
  subproject_files_in_subproject?: boolean | null;

  map_presentation_crs?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.projects_history
 * System-versioned history of projects. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface ProjectsHistoryMutator {
  project_id?: string;

  account_id?: string | null;

  name?: string | null;

  label?: string | null;

  type?: ProjectTypesEnum | null;

  subproject_name_singular?: string | null;

  subproject_name_plural?: string | null;

  subproject_name_singular_en?: string | null;

  subproject_name_plural_en?: string | null;

  subproject_name_singular_fr?: string | null;

  subproject_name_plural_fr?: string | null;

  subproject_name_singular_it?: string | null;

  subproject_name_plural_it?: string | null;

  subproject_order_by?: string | null;

  places_label_by?: string | null;

  places_order_by?: string | null;

  goals_label_by?: string | null;

  goal_reports_label_by?: string | null;

  goal_reports_order_by?: string | null;

  actions_default_unit_id?: string | null;

  checks_default_unit_id?: string | null;

  check_taxa_default_unit_id?: string | null;

  action_taxa_default_unit_id?: string | null;

  check_reports_default_unit_id?: string | null;

  action_reports_default_unit_id?: string | null;

  values_on_multiple_levels?: string | null;

  multiple_action_quantities_on_same_level?: string | null;

  multiple_check_quantities_on_same_level?: string | null;

  wms_layers?: boolean | null;

  vector_layers?: boolean | null;

  project_reports?: boolean | null;

  subproject_reports?: boolean | null;

  goals?: boolean | null;

  occurrences?: boolean | null;

  taxa?: boolean | null;

  charts?: boolean | null;

  enable_histories?: boolean | null;

  data?: unknown | null;

  files_offline?: boolean | null;

  files_active_projects?: boolean | null;

  project_files_in_project?: boolean | null;

  files_active_subprojects?: boolean | null;

  subproject_files_in_subproject?: boolean | null;

  map_presentation_crs?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
