// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';

/** Identifier type for public.project_report_designs */
export type ProjectReportDesignsProjectReportDesignId = string & { __brand: 'public.project_report_designs' };

/**
 * Represents the table public.project_report_designs
 * Customizable designs for project reports, stored as JSON.
 */
export default interface ProjectReportDesigns {
  project_report_design_id: ProjectReportDesignsProjectReportDesignId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  /** JSON design of the project report design. */
  design: unknown | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.project_report_designs
 * Customizable designs for project reports, stored as JSON.
 */
export interface ProjectReportDesignsInitializer {
  /** Default value: uuid_generate_v7() */
  project_report_design_id?: ProjectReportDesignsProjectReportDesignId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** JSON design of the project report design. */
  design?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.project_report_designs
 * Customizable designs for project reports, stored as JSON.
 */
export interface ProjectReportDesignsMutator {
  project_report_design_id?: ProjectReportDesignsProjectReportDesignId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** JSON design of the project report design. */
  design?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
