// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.project_types_enum */
enum ProjectTypesEnum {
  species = 'species',
  biotope = 'biotope',
};

export default ProjectTypesEnum;
