// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.qcs */
export type QcsQcsId = string & { __brand: 'public.qcs' };

/**
 * Represents the table public.qcs
 * Quality control rules for data validation. No history tracking needed as these are root-level configuration managed by administrators.
 */
export default interface Qcs {
  qcs_id: QcsQcsId;

  name: string | null;

  /** The table this quality control applies to. E.g. observations, places, actions, checks. Used to group and sort qcs in the ui */
  table_name: string | null;

  /** The place level this quality control applies to. 1 or 2. Only relevant when table_name is places, actions or checks */
  place_level: number | null;

  label_de: string | null;

  label_en: string | null;

  label_fr: string | null;

  label_it: string | null;

  description: string | null;

  sort: number | null;

  is_root_level: boolean | null;

  is_project_level: boolean | null;

  is_subproject_level: boolean | null;

  filter_by_year: boolean | null;

  sql: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;
}

/**
 * Represents the initializer for the table public.qcs
 * Quality control rules for data validation. No history tracking needed as these are root-level configuration managed by administrators.
 */
export interface QcsInitializer {
  /** Default value: uuid_generate_v7() */
  qcs_id?: QcsQcsId;

  name?: string | null;

  /** The table this quality control applies to. E.g. observations, places, actions, checks. Used to group and sort qcs in the ui */
  table_name?: string | null;

  /** The place level this quality control applies to. 1 or 2. Only relevant when table_name is places, actions or checks */
  place_level?: number | null;

  label_de?: string | null;

  label_en?: string | null;

  label_fr?: string | null;

  label_it?: string | null;

  description?: string | null;

  sort?: number | null;

  /** Default value: false */
  is_root_level?: boolean | null;

  /** Default value: false */
  is_project_level?: boolean | null;

  /** Default value: false */
  is_subproject_level?: boolean | null;

  /** Default value: false */
  filter_by_year?: boolean | null;

  sql?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;
}

/**
 * Represents the mutator for the table public.qcs
 * Quality control rules for data validation. No history tracking needed as these are root-level configuration managed by administrators.
 */
export interface QcsMutator {
  qcs_id?: QcsQcsId;

  name?: string | null;

  /** The table this quality control applies to. E.g. observations, places, actions, checks. Used to group and sort qcs in the ui */
  table_name?: string | null;

  /** The place level this quality control applies to. 1 or 2. Only relevant when table_name is places, actions or checks */
  place_level?: number | null;

  label_de?: string | null;

  label_en?: string | null;

  label_fr?: string | null;

  label_it?: string | null;

  description?: string | null;

  sort?: number | null;

  is_root_level?: boolean | null;

  is_project_level?: boolean | null;

  is_subproject_level?: boolean | null;

  filter_by_year?: boolean | null;

  sql?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period?: string;
}
