// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjectsProjectId } from './Projects';
import type { SubprojectsSubprojectId } from './Subprojects';
import type { QcsQcsId } from './Qcs';

/** Identifier type for public.qcs_assignment */
export type QcsAssignmentQcsAssignmentId = string & { __brand: 'public.qcs_assignment' };

/**
 * Represents the table public.qcs_assignment
 * Quality controls assigned to a project or subproject. The level(s) of applicability (root, project, subproject) are defined on the qcs table itself.
 */
export default interface QcsAssignment {
  qcs_assignment_id: QcsAssignmentQcsAssignmentId;

  project_id: ProjectsProjectId | null;

  subproject_id: SubprojectsSubprojectId | null;

  qc_id: QcsQcsId;

  label: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.qcs_assignment
 * Quality controls assigned to a project or subproject. The level(s) of applicability (root, project, subproject) are defined on the qcs table itself.
 */
export interface QcsAssignmentInitializer {
  /** Default value: uuid_generate_v7() */
  qcs_assignment_id?: QcsAssignmentQcsAssignmentId;

  project_id?: ProjectsProjectId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  qc_id: QcsQcsId;

  label?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.qcs_assignment
 * Quality controls assigned to a project or subproject. The level(s) of applicability (root, project, subproject) are defined on the qcs table itself.
 */
export interface QcsAssignmentMutator {
  qcs_assignment_id?: QcsAssignmentQcsAssignmentId;

  project_id?: ProjectsProjectId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  qc_id?: QcsQcsId;

  label?: string | null;

  /** System period maintained by temporal_tables for auditing and historic queries. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
