// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';
import type { UsersUserId } from './Users';
import type { UserRolesRole } from './UserRoles';

/** Identifier type for public.subproject_users */
export type SubprojectUsersSubprojectUserId = string & { __brand: 'public.subproject_users' };

/**
 * Represents the table public.subproject_users
 * A way to give users access to subprojects (without giving them access to the whole project). TODO: define what data from the project the user can see.
 */
export default interface SubprojectUsers {
  subproject_user_id: SubprojectUsersSubprojectUserId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  subproject_id: SubprojectsSubprojectId | null;

  user_id: UsersUserId | null;

  /** TODO: One of: "manager", "editor", "reader". Preset: "reader" */
  role: UserRolesRole | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.subproject_users
 * A way to give users access to subprojects (without giving them access to the whole project). TODO: define what data from the project the user can see.
 */
export interface SubprojectUsersInitializer {
  /** Default value: uuid_generate_v7() */
  subproject_user_id?: SubprojectUsersSubprojectUserId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  user_id?: UsersUserId | null;

  /** TODO: One of: "manager", "editor", "reader". Preset: "reader" */
  role?: UserRolesRole | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.subproject_users
 * A way to give users access to subprojects (without giving them access to the whole project). TODO: define what data from the project the user can see.
 */
export interface SubprojectUsersMutator {
  subproject_user_id?: SubprojectUsersSubprojectUserId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  user_id?: UsersUserId | null;

  /** TODO: One of: "manager", "editor", "reader". Preset: "reader" */
  role?: UserRolesRole | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
