// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SubprojectsSubprojectId } from './Subprojects';
import type { QcsQcsId } from './Qcs';

/** Identifier type for public.subproject_qcs */
export type SubprojectQcsSubprojectQcId = string & { __brand: 'public.subproject_qcs' };

/**
 * Represents the table public.subproject_qcs
 * Quality controls used in a subproject. Ensure not to create false positives by only applying quality controls that are relevant for the data in a subproject.
 */
export default interface SubprojectQcs {
  subproject_qc_id: SubprojectQcsSubprojectQcId;

  subproject_id: SubprojectsSubprojectId;

  qc_id: QcsQcsId;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.subproject_qcs
 * Quality controls used in a subproject. Ensure not to create false positives by only applying quality controls that are relevant for the data in a subproject.
 */
export interface SubprojectQcsInitializer {
  /** Default value: uuid_generate_v7() */
  subproject_qc_id?: SubprojectQcsSubprojectQcId;

  subproject_id: SubprojectsSubprojectId;

  qc_id: QcsQcsId;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.subproject_qcs
 * Quality controls used in a subproject. Ensure not to create false positives by only applying quality controls that are relevant for the data in a subproject.
 */
export interface SubprojectQcsMutator {
  subproject_qc_id?: SubprojectQcsSubprojectQcId;

  subproject_id?: SubprojectsSubprojectId;

  qc_id?: QcsQcsId;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
