// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the table public.subprojects_history
 * System-versioned history of subprojects. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface SubprojectsHistory {
  subproject_id: string;

  account_id: string | null;

  project_id: string | null;

  name: string | null;

  start_year: number | null;

  end_year: number | null;

  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;
}

/**
 * Represents the initializer for the table public.subprojects_history
 * System-versioned history of subprojects. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface SubprojectsHistoryInitializer {
  subproject_id: string;

  account_id?: string | null;

  project_id?: string | null;

  name?: string | null;

  start_year?: number | null;

  end_year?: number | null;

  data?: unknown | null;

  label?: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;
}

/**
 * Represents the mutator for the table public.subprojects_history
 * System-versioned history of subprojects. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface SubprojectsHistoryMutator {
  subproject_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  name?: string | null;

  start_year?: number | null;

  end_year?: number | null;

  data?: unknown | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;
}
