// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';

/** Identifier type for public.subproject_reports */
export type SubprojectReportsSubprojectReportId = string & { __brand: 'public.subproject_reports' };

/**
 * Represents the table public.subproject_reports
 * Reporting on the success of subprojects.
 */
export default interface SubprojectReports {
  subproject_report_id: SubprojectReportsSubprojectReportId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  subproject_id: SubprojectsSubprojectId | null;

  /** Year of report. Preset: current year */
  year: number | null;

  /** Room for subproject report specific data, defined in "fields" table */
  data: unknown | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.subproject_reports
 * Reporting on the success of subprojects.
 */
export interface SubprojectReportsInitializer {
  /** Default value: uuid_generate_v7() */
  subproject_report_id?: SubprojectReportsSubprojectReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /**
   * Year of report. Preset: current year
   * Default value: date_part('year'::text, (now())::date)
   */
  year?: number | null;

  /** Room for subproject report specific data, defined in "fields" table */
  data?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.subproject_reports
 * Reporting on the success of subprojects.
 */
export interface SubprojectReportsMutator {
  subproject_report_id?: SubprojectReportsSubprojectReportId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /** Year of report. Preset: current year */
  year?: number | null;

  /** Room for subproject report specific data, defined in "fields" table */
  data?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
