// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the table public.subproject_taxa_history
 * System-versioned history of subproject_taxa. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface SubprojectTaxaHistory {
  subproject_taxon_id: string;

  account_id: string | null;

  subproject_id: string | null;

  taxon_id: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;
}

/**
 * Represents the initializer for the table public.subproject_taxa_history
 * System-versioned history of subproject_taxa. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface SubprojectTaxaHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  subproject_taxon_id?: string;

  account_id?: string | null;

  subproject_id?: string | null;

  taxon_id?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;
}

/**
 * Represents the mutator for the table public.subproject_taxa_history
 * System-versioned history of subproject_taxa. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface SubprojectTaxaHistoryMutator {
  subproject_taxon_id?: string;

  account_id?: string | null;

  subproject_id?: string | null;

  taxon_id?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;
}
