// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';

/** Identifier type for public.subproject_report_designs */
export type SubprojectReportDesignsSubprojectReportDesignId = string & { __brand: 'public.subproject_report_designs' };

/**
 * Represents the table public.subproject_report_designs
 * Design of subproject reports, stored as JSON.
 */
export default interface SubprojectReportDesigns {
  subproject_report_design_id: SubprojectReportDesignsSubprojectReportDesignId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  subproject_id: SubprojectsSubprojectId | null;

  /** JSON design of the subproject report. */
  design: unknown | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.subproject_report_designs
 * Design of subproject reports, stored as JSON.
 */
export interface SubprojectReportDesignsInitializer {
  /** Default value: uuid_generate_v7() */
  subproject_report_design_id?: SubprojectReportDesignsSubprojectReportDesignId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /** JSON design of the subproject report. */
  design?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.subproject_report_designs
 * Design of subproject reports, stored as JSON.
 */
export interface SubprojectReportDesignsMutator {
  subproject_report_design_id?: SubprojectReportDesignsSubprojectReportDesignId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /** JSON design of the subproject report. */
  design?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
