// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SubprojectsSubprojectId } from './Subprojects';
import type { TaxaTaxonId } from './Taxa';

/** Identifier type for public.subproject_taxa */
export type SubprojectTaxaSubprojectTaxonId = string & { __brand: 'public.subproject_taxa' };

/**
 * Represents the table public.subproject_taxa
 * list wor what taxa data is managed in the subproject.
 */
export default interface SubprojectTaxa {
  subproject_taxon_id: SubprojectTaxaSubprojectTaxonId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  subproject_id: SubprojectsSubprojectId | null;

  /** taxons that are meant in this subproject. Can be multiple, for instance synonyms of a single taxonomy or of different taxonomies. A taxon should be used in only one subproject. */
  taxon_id: TaxaTaxonId | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.subproject_taxa
 * list wor what taxa data is managed in the subproject.
 */
export interface SubprojectTaxaInitializer {
  /** Default value: uuid_generate_v7() */
  subproject_taxon_id?: SubprojectTaxaSubprojectTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /** taxons that are meant in this subproject. Can be multiple, for instance synonyms of a single taxonomy or of different taxonomies. A taxon should be used in only one subproject. */
  taxon_id?: TaxaTaxonId | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.subproject_taxa
 * list wor what taxa data is managed in the subproject.
 */
export interface SubprojectTaxaMutator {
  subproject_taxon_id?: SubprojectTaxaSubprojectTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  subproject_id?: SubprojectsSubprojectId | null;

  /** taxons that are meant in this subproject. Can be multiple, for instance synonyms of a single taxonomy or of different taxonomies. A taxon should be used in only one subproject. */
  taxon_id?: TaxaTaxonId | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
