// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { TaxonomiesTaxonomyId } from './Taxonomies';

/** Identifier type for public.taxa */
export type TaxaTaxonId = string & { __brand: 'public.taxa' };

/** Represents the table public.taxa */
export default interface Taxa {
  taxon_id: TaxaTaxonId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  taxonomy_id: TaxonomiesTaxonomyId | null;

  /** Name of taxon, like "Pulsatilla vulgaris" */
  name: string | null;

  /** ID of taxon as used in the source taxonomy */
  id_in_source: string | null;

  /** Data as received from source */
  data: unknown | null;

  /** URL of taxon, like "https://www.infoflora.ch/de/flora/pulsatilla-vulgaris.html" */
  url: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.taxa */
export interface TaxaInitializer {
  /** Default value: uuid_generate_v7() */
  taxon_id?: TaxaTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  taxonomy_id?: TaxonomiesTaxonomyId | null;

  /** Name of taxon, like "Pulsatilla vulgaris" */
  name?: string | null;

  /** ID of taxon as used in the source taxonomy */
  id_in_source?: string | null;

  /** Data as received from source */
  data?: unknown | null;

  /** URL of taxon, like "https://www.infoflora.ch/de/flora/pulsatilla-vulgaris.html" */
  url?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.taxa */
export interface TaxaMutator {
  taxon_id?: TaxaTaxonId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  taxonomy_id?: TaxonomiesTaxonomyId | null;

  /** Name of taxon, like "Pulsatilla vulgaris" */
  name?: string | null;

  /** ID of taxon as used in the source taxonomy */
  id_in_source?: string | null;

  /** Data as received from source */
  data?: unknown | null;

  /** URL of taxon, like "https://www.infoflora.ch/de/flora/pulsatilla-vulgaris.html" */
  url?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
