// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.taxonomy_types */
export type TaxonomyTypesType = string & { __brand: 'public.taxonomy_types' };

/** Represents the table public.taxonomy_types */
export default interface TaxonomyTypes {
  type: TaxonomyTypesType;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.taxonomy_types */
export interface TaxonomyTypesInitializer {
  type: TaxonomyTypesType;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.taxonomy_types */
export interface TaxonomyTypesMutator {
  type?: TaxonomyTypesType;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
