// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as TaxonomyTypesEnum } from './TaxonomyTypesEnum';

/**
 * Represents the table public.taxonomies_history
 * System-versioned history of taxonomies. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface TaxonomiesHistory {
  taxonomy_id: string;

  account_id: string | null;

  project_id: string | null;

  type: TaxonomyTypesEnum | null;

  unit_id: string | null;

  name: string | null;

  url: string | null;

  obsolete: boolean | null;

  data: unknown | null;

  label: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.taxonomies_history
 * System-versioned history of taxonomies. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface TaxonomiesHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  taxonomy_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  type?: TaxonomyTypesEnum | null;

  unit_id?: string | null;

  name?: string | null;

  url?: string | null;

  /** Default value: false */
  obsolete?: boolean | null;

  data?: unknown | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.taxonomies_history
 * System-versioned history of taxonomies. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface TaxonomiesHistoryMutator {
  taxonomy_id?: string;

  account_id?: string | null;

  project_id?: string | null;

  type?: TaxonomyTypesEnum | null;

  unit_id?: string | null;

  name?: string | null;

  url?: string | null;

  obsolete?: boolean | null;

  data?: unknown | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
