// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.taxonomy_types_enum */
enum TaxonomyTypesEnum {
  species = 'species',
  biotope = 'biotope',
};

export default TaxonomyTypesEnum;
