// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';
import type { ListsListId } from './Lists';
import type { default as UnitTypesEnum } from './UnitTypesEnum';

/** Identifier type for public.units */
export type UnitsUnitId = string & { __brand: 'public.units' };

/**
 * Represents the table public.units
 * Manage units of values. These units can then be used for values of actions, checks, reports, goals, taxa
 */
export default interface Units {
  unit_id: UnitsUnitId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  /** Optional list of allowed values for this unit. When set, check/action value inputs use the list values instead of a free text/number field. */
  list_id: ListsListId | null;

  /** Name of unit, like "Anzahl" */
  name: string | null;

  /** Whether values of this unit can be summed (also: averaged). Else: distribution of count per value. Preset: false */
  summable: boolean | null;

  sort: number | null;

  /** One of: "integer", "numeric", "text". Preset: "integer" */
  type: UnitTypesEnum | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.units
 * Manage units of values. These units can then be used for values of actions, checks, reports, goals, taxa
 */
export interface UnitsInitializer {
  /** Default value: uuid_generate_v7() */
  unit_id?: UnitsUnitId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** Optional list of allowed values for this unit. When set, check/action value inputs use the list values instead of a free text/number field. */
  list_id?: ListsListId | null;

  /** Name of unit, like "Anzahl" */
  name?: string | null;

  /**
   * Whether values of this unit can be summed (also: averaged). Else: distribution of count per value. Preset: false
   * Default value: false
   */
  summable?: boolean | null;

  sort?: number | null;

  /** One of: "integer", "numeric", "text". Preset: "integer" */
  type?: UnitTypesEnum | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.units
 * Manage units of values. These units can then be used for values of actions, checks, reports, goals, taxa
 */
export interface UnitsMutator {
  unit_id?: UnitsUnitId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** Optional list of allowed values for this unit. When set, check/action value inputs use the list values instead of a free text/number field. */
  list_id?: ListsListId | null;

  /** Name of unit, like "Anzahl" */
  name?: string | null;

  /** Whether values of this unit can be summed (also: averaged). Else: distribution of count per value. Preset: false */
  summable?: boolean | null;

  sort?: number | null;

  /** One of: "integer", "numeric", "text". Preset: "integer" */
  type?: UnitTypesEnum | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
