// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.unit_types */
export type UnitTypesType = string & { __brand: 'public.unit_types' };

/** Represents the table public.unit_types */
export default interface UnitTypes {
  type: UnitTypesType;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.unit_types */
export interface UnitTypesInitializer {
  type: UnitTypesType;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.unit_types */
export interface UnitTypesMutator {
  type?: UnitTypesType;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
