// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.unit_types_enum */
enum UnitTypesEnum {
  integer = 'integer',
  numeric = 'numeric',
  text = 'text',
};

export default UnitTypesEnum;
