// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';
import type { UnitTypesType } from './UnitTypes';
import type { ListsListId } from './Lists';

/** Identifier type for public.units */
export type UnitsUnitId = string & { __brand: 'public.units' };

/**
 * Represents the table public.units
 * Manage units of values. These units can then be used for values of actions, checks, reports, goals, taxa
 */
export default interface Units {
  unit_id: UnitsUnitId;

  /** redundant account_id enhances data safety */
  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId | null;

  /** Whether to use this unit for action values. Preset: false */
  use_for_action_values: boolean | null;

  /** Whether to use this unit for action report values. Preset: false */
  use_for_action_report_values: boolean | null;

  /** Whether to use this unit for check values. Preset: false */
  use_for_check_values: boolean | null;

  /** Whether to use this unit for place report values. Preset: false */
  use_for_place_report_values: boolean | null;

  /** Whether to use this unit for goal report values. Preset: false */
  use_for_goal_report_values: boolean | null;

  /** Whether to use this unit for subproject taxa. Preset: false */
  use_for_subproject_taxa: boolean | null;

  /** Whether to use this unit for check taxa. Preset: false */
  use_for_check_taxa: boolean | null;

  /** Name of unit, like "Anzahl" */
  name: string | null;

  /** Whether values of this unit can be summed. Else: distribution of count per value. Preset: false */
  summable: boolean | null;

  sort: number | null;

  /** One of: "integer", "numeric", "text". Preset: "integer" */
  type: UnitTypesType | null;

  list_id: ListsListId | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.units
 * Manage units of values. These units can then be used for values of actions, checks, reports, goals, taxa
 */
export interface UnitsInitializer {
  /** Default value: uuid_generate_v7() */
  unit_id?: UnitsUnitId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /**
   * Whether to use this unit for action values. Preset: false
   * Default value: false
   */
  use_for_action_values?: boolean | null;

  /**
   * Whether to use this unit for action report values. Preset: false
   * Default value: false
   */
  use_for_action_report_values?: boolean | null;

  /**
   * Whether to use this unit for check values. Preset: false
   * Default value: false
   */
  use_for_check_values?: boolean | null;

  /**
   * Whether to use this unit for place report values. Preset: false
   * Default value: false
   */
  use_for_place_report_values?: boolean | null;

  /**
   * Whether to use this unit for goal report values. Preset: false
   * Default value: false
   */
  use_for_goal_report_values?: boolean | null;

  /**
   * Whether to use this unit for subproject taxa. Preset: false
   * Default value: false
   */
  use_for_subproject_taxa?: boolean | null;

  /**
   * Whether to use this unit for check taxa. Preset: false
   * Default value: false
   */
  use_for_check_taxa?: boolean | null;

  /** Name of unit, like "Anzahl" */
  name?: string | null;

  /**
   * Whether values of this unit can be summed. Else: distribution of count per value. Preset: false
   * Default value: false
   */
  summable?: boolean | null;

  sort?: number | null;

  /** One of: "integer", "numeric", "text". Preset: "integer" */
  type?: UnitTypesType | null;

  list_id?: ListsListId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.units
 * Manage units of values. These units can then be used for values of actions, checks, reports, goals, taxa
 */
export interface UnitsMutator {
  unit_id?: UnitsUnitId;

  /** redundant account_id enhances data safety */
  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId | null;

  /** Whether to use this unit for action values. Preset: false */
  use_for_action_values?: boolean | null;

  /** Whether to use this unit for action report values. Preset: false */
  use_for_action_report_values?: boolean | null;

  /** Whether to use this unit for check values. Preset: false */
  use_for_check_values?: boolean | null;

  /** Whether to use this unit for place report values. Preset: false */
  use_for_place_report_values?: boolean | null;

  /** Whether to use this unit for goal report values. Preset: false */
  use_for_goal_report_values?: boolean | null;

  /** Whether to use this unit for subproject taxa. Preset: false */
  use_for_subproject_taxa?: boolean | null;

  /** Whether to use this unit for check taxa. Preset: false */
  use_for_check_taxa?: boolean | null;

  /** Name of unit, like "Anzahl" */
  name?: string | null;

  /** Whether values of this unit can be summed. Else: distribution of count per value. Preset: false */
  summable?: boolean | null;

  sort?: number | null;

  /** One of: "integer", "numeric", "text". Preset: "integer" */
  type?: UnitTypesType | null;

  list_id?: ListsListId | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
