// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersUserId = string & { __brand: 'public.users' };

/**
 * Represents the table public.users
 * Goal: manage users and authorize them
 */
export default interface Users {
  user_id: UsersUserId;

  /** email needs to be unique. project manager can list project user by email before this user creates an own login (thus has no user_id yet) */
  email: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.users
 * Goal: manage users and authorize them
 */
export interface UsersInitializer {
  /** Default value: uuid_generate_v7() */
  user_id?: UsersUserId;

  /** email needs to be unique. project manager can list project user by email before this user creates an own login (thus has no user_id yet) */
  email?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.users
 * Goal: manage users and authorize them
 */
export interface UsersMutator {
  user_id?: UsersUserId;

  /** email needs to be unique. project manager can list project user by email before this user creates an own login (thus has no user_id yet) */
  email?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
