// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.user_roles */
export type UserRolesRole = string & { __brand: 'public.user_roles' };

/** Represents the table public.user_roles */
export default interface UserRoles {
  role: UserRolesRole;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.user_roles */
export interface UserRolesInitializer {
  role: UserRolesRole;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.user_roles */
export interface UserRolesMutator {
  role?: UserRolesRole;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
