// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.user_roles_enum */
enum UserRolesEnum {
  manager = 'manager',
  editor = 'editor',
  reader = 'reader',
};

export default UserRolesEnum;
