// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { UsersUserId } from './Users';
import type { MessagesMessageId } from './Messages';

/** Identifier type for public.user_messages */
export type UserMessagesUserMessageId = string & { __brand: 'public.user_messages' };

/** Represents the table public.user_messages */
export default interface UserMessages {
  user_message_id: UserMessagesUserMessageId;

  account_id: AccountsAccountId | null;

  user_id: UsersUserId | null;

  message_id: MessagesMessageId | null;

  read: boolean | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.user_messages */
export interface UserMessagesInitializer {
  /** Default value: uuid_generate_v7() */
  user_message_id?: UserMessagesUserMessageId;

  account_id?: AccountsAccountId | null;

  user_id?: UsersUserId | null;

  message_id?: MessagesMessageId | null;

  /** Default value: false */
  read?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.user_messages */
export interface UserMessagesMutator {
  user_message_id?: UserMessagesUserMessageId;

  account_id?: AccountsAccountId | null;

  user_id?: UsersUserId | null;

  message_id?: MessagesMessageId | null;

  read?: boolean | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
