// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface uuid_generate_v7_params {
}

/** Return type for uuid_generate_v7 */
export type uuid_generate_v7_return_type = string;
