// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as VectorLayerMarkerTypesEnum } from './VectorLayerMarkerTypesEnum';
import type { default as VectorLayerLineCapsEnum } from './VectorLayerLineCapsEnum';
import type { default as VectorLayerLineJoinsEnum } from './VectorLayerLineJoinsEnum';
import type { default as VectorLayerFillRulesEnum } from './VectorLayerFillRulesEnum';

/**
 * Represents the table public.vector_layer_displays_history
 * System-versioned history of vector_layer_displays. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export default interface VectorLayerDisplaysHistory {
  vector_layer_display_id: string;

  account_id: string | null;

  vector_layer_id: string | null;

  display_property_value: string | null;

  marker_type: VectorLayerMarkerTypesEnum | null;

  circle_marker_radius: number | null;

  marker_symbol: string | null;

  marker_size: number | null;

  stroke: boolean | null;

  color: string | null;

  weight: number | null;

  line_cap: VectorLayerLineCapsEnum | null;

  line_join: VectorLayerLineJoinsEnum | null;

  dash_array: string | null;

  dash_offset: string | null;

  fill: boolean | null;

  fill_color: string | null;

  fill_opacity_percent: number | null;

  fill_rule: VectorLayerFillRulesEnum | null;

  label: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.vector_layer_displays_history
 * System-versioned history of vector_layer_displays. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface VectorLayerDisplaysHistoryInitializer {
  /** Default value: uuid_generate_v7() */
  vector_layer_display_id?: string;

  account_id?: string | null;

  vector_layer_id?: string | null;

  display_property_value?: string | null;

  /** Default value: 'circle'::vector_layer_marker_types_enum */
  marker_type?: VectorLayerMarkerTypesEnum | null;

  /** Default value: 8 */
  circle_marker_radius?: number | null;

  marker_symbol?: string | null;

  /** Default value: 16 */
  marker_size?: number | null;

  /** Default value: true */
  stroke?: boolean | null;

  /** Default value: '#3388ff'::text */
  color?: string | null;

  /** Default value: 3 */
  weight?: number | null;

  /** Default value: 'round'::vector_layer_line_caps_enum */
  line_cap?: VectorLayerLineCapsEnum | null;

  /** Default value: 'round'::vector_layer_line_joins_enum */
  line_join?: VectorLayerLineJoinsEnum | null;

  dash_array?: string | null;

  dash_offset?: string | null;

  /** Default value: true */
  fill?: boolean | null;

  fill_color?: string | null;

  /** Default value: 100 */
  fill_opacity_percent?: number | null;

  /** Default value: 'evenodd'::vector_layer_fill_rules_enum */
  fill_rule?: VectorLayerFillRulesEnum | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period: string;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.vector_layer_displays_history
 * System-versioned history of vector_layer_displays. Managed by temporal_tables and partitioned yearly by updated_at.
 */
export interface VectorLayerDisplaysHistoryMutator {
  vector_layer_display_id?: string;

  account_id?: string | null;

  vector_layer_id?: string | null;

  display_property_value?: string | null;

  marker_type?: VectorLayerMarkerTypesEnum | null;

  circle_marker_radius?: number | null;

  marker_symbol?: string | null;

  marker_size?: number | null;

  stroke?: boolean | null;

  color?: string | null;

  weight?: number | null;

  line_cap?: VectorLayerLineCapsEnum | null;

  line_join?: VectorLayerLineJoinsEnum | null;

  dash_array?: string | null;

  dash_offset?: string | null;

  fill?: boolean | null;

  fill_color?: string | null;

  fill_opacity_percent?: number | null;

  fill_rule?: VectorLayerFillRulesEnum | null;

  label?: string | null;

  /** System period written by temporal_tables. lower(sys_period) is when the row version became current, upper(sys_period) when it stopped being current. */
  sys_period?: string;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
