// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.vector_layer_fill_rules_enum */
enum VectorLayerFillRulesEnum {
  nonzero = 'nonzero',
  evenodd = 'evenodd',
};

export default VectorLayerFillRulesEnum;
