// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.vector_layer_own_tables */
export type VectorLayerOwnTablesOwnTable = string & { __brand: 'public.vector_layer_own_tables' };

/** Represents the table public.vector_layer_own_tables */
export default interface VectorLayerOwnTables {
  own_table: VectorLayerOwnTablesOwnTable;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.vector_layer_own_tables */
export interface VectorLayerOwnTablesInitializer {
  own_table: VectorLayerOwnTablesOwnTable;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.vector_layer_own_tables */
export interface VectorLayerOwnTablesMutator {
  own_table?: VectorLayerOwnTablesOwnTable;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
