// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.vector_layer_line_caps_enum */
enum VectorLayerLineCapsEnum {
  butt = 'butt',
  round = 'round',
  square = 'square',
};

export default VectorLayerLineCapsEnum;
