// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { VectorLayersVectorLayerId } from './VectorLayers';

/** Identifier type for public.vector_layer_geoms */
export type VectorLayerGeomsVectorLayerGeomId = string & { __brand: 'public.vector_layer_geoms' };

/**
 * Represents the table public.vector_layer_geoms
 * Goal: Save vector layers client side for 1. offline usage 2. better filtering (to viewport) 3. enable displaying by field values. Data is downloaded when manager configures vector layer. Not versioned (not recorded and only added by manager).
 */
export default interface VectorLayerGeoms {
  vector_layer_geom_id: VectorLayerGeomsVectorLayerGeomId;

  account_id: AccountsAccountId | null;

  vector_layer_id: VectorLayersVectorLayerId | null;

  /** geometry-collection of this row */
  geometry: unknown | null;

  /** properties of this row */
  properties: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_sw_lng: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_sw_lat: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_ne_lng: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_ne_lat: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.vector_layer_geoms
 * Goal: Save vector layers client side for 1. offline usage 2. better filtering (to viewport) 3. enable displaying by field values. Data is downloaded when manager configures vector layer. Not versioned (not recorded and only added by manager).
 */
export interface VectorLayerGeomsInitializer {
  /** Default value: uuid_generate_v7() */
  vector_layer_geom_id?: VectorLayerGeomsVectorLayerGeomId;

  account_id?: AccountsAccountId | null;

  vector_layer_id?: VectorLayersVectorLayerId | null;

  /** geometry-collection of this row */
  geometry?: unknown | null;

  /** properties of this row */
  properties?: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_sw_lng?: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_sw_lat?: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_ne_lng?: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_ne_lat?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.vector_layer_geoms
 * Goal: Save vector layers client side for 1. offline usage 2. better filtering (to viewport) 3. enable displaying by field values. Data is downloaded when manager configures vector layer. Not versioned (not recorded and only added by manager).
 */
export interface VectorLayerGeomsMutator {
  vector_layer_geom_id?: VectorLayerGeomsVectorLayerGeomId;

  account_id?: AccountsAccountId | null;

  vector_layer_id?: VectorLayersVectorLayerId | null;

  /** geometry-collection of this row */
  geometry?: unknown | null;

  /** properties of this row */
  properties?: unknown | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_sw_lng?: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_sw_lat?: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_ne_lng?: number | null;

  /** bbox of the geometry. Set client-side on every change of geometry. Used to filter geometries client-side for viewport */
  bbox_ne_lat?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
