// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.vector_layer_types */
export type VectorLayerTypesType = string & { __brand: 'public.vector_layer_types' };

/** Represents the table public.vector_layer_types */
export default interface VectorLayerTypes {
  type: VectorLayerTypesType;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.vector_layer_types */
export interface VectorLayerTypesInitializer {
  type: VectorLayerTypesType;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.vector_layer_types */
export interface VectorLayerTypesMutator {
  type?: VectorLayerTypesType;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
