// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.vector_layer_marker_types_enum */
enum VectorLayerMarkerTypesEnum {
  circle = 'circle',
  marker = 'marker',
};

export default VectorLayerMarkerTypesEnum;
