// This file has been manually updated to reflect the enum type
export type VectorLayerTypesEnum =
  | 'wfs'
  | 'upload'
  | 'own'
  | 'places1'
  | 'places2'
  | 'actions1'
  | 'actions2'
  | 'checks1'
  | 'checks2'
  | 'observations_assigned1'
  | 'observations_assigned_lines1'
  | 'observations_assigned2'
  | 'observations_assigned_lines2'
  | 'observations_to_assess'
  | 'observations_not_to_assign'
