// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.vector_layer_line_joins_enum */
enum VectorLayerLineJoinsEnum {
  arcs = 'arcs',
  bevel = 'bevel',
  miter = 'miter',
  'miter-clip' = 'miter-clip',
  round = 'round',
};

export default VectorLayerLineJoinsEnum;
