// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.vector_layer_line_joins */
export type VectorLayerLineJoinsLineJoin = string & { __brand: 'public.vector_layer_line_joins' };

/** Represents the table public.vector_layer_line_joins */
export default interface VectorLayerLineJoins {
  line_join: VectorLayerLineJoinsLineJoin;

  sort: number | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.vector_layer_line_joins */
export interface VectorLayerLineJoinsInitializer {
  line_join: VectorLayerLineJoinsLineJoin;

  sort?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.vector_layer_line_joins */
export interface VectorLayerLineJoinsMutator {
  line_join?: VectorLayerLineJoinsLineJoin;

  sort?: number | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
