// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.vector_layer_own_tables_enum */
enum VectorLayerOwnTablesEnum {
  places = 'places',
  actions = 'actions',
  checks = 'checks',
  observations_assigned = 'observations_assigned',
  observations_assigned_lines = 'observations_assigned_lines',
  observations_to_assess = 'observations_to_assess',
  observations_not_to_assign = 'observations_not_to_assign',
};

export default VectorLayerOwnTablesEnum;
