// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';

/** Identifier type for public.wfs_services */
export type WfsServicesWfsServiceId = string & { __brand: 'public.wfs_services' };

/**
 * Represents the table public.wfs_services
 * A layer of a WFS service.
 */
export default interface WfsServices {
  wfs_service_id: WfsServicesWfsServiceId;

  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId;

  url: string | null;

  version: string | null;

  info_formats: unknown | null;

  info_format: string | null;

  /** It seems that this is the crs bbox calls have to be made in */
  default_crs: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.wfs_services
 * A layer of a WFS service.
 */
export interface WfsServicesInitializer {
  /** Default value: uuid_generate_v7() */
  wfs_service_id?: WfsServicesWfsServiceId;

  account_id?: AccountsAccountId | null;

  project_id: ProjectsProjectId;

  url?: string | null;

  version?: string | null;

  info_formats?: unknown | null;

  info_format?: string | null;

  /** It seems that this is the crs bbox calls have to be made in */
  default_crs?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.wfs_services
 * A layer of a WFS service.
 */
export interface WfsServicesMutator {
  wfs_service_id?: WfsServicesWfsServiceId;

  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId;

  url?: string | null;

  version?: string | null;

  info_formats?: unknown | null;

  info_format?: string | null;

  /** It seems that this is the crs bbox calls have to be made in */
  default_crs?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
