// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { WfsServicesWfsServiceId } from './WfsServices';

/** Identifier type for public.wfs_service_layers */
export type WfsServiceLayersWfsServiceLayerId = string & { __brand: 'public.wfs_service_layers' };

/** Represents the table public.wfs_service_layers */
export default interface WfsServiceLayers {
  wfs_service_layer_id: WfsServiceLayersWfsServiceLayerId;

  account_id: AccountsAccountId | null;

  wfs_service_id: WfsServicesWfsServiceId | null;

  name: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.wfs_service_layers */
export interface WfsServiceLayersInitializer {
  /** Default value: uuid_generate_v7() */
  wfs_service_layer_id?: WfsServiceLayersWfsServiceLayerId;

  account_id?: AccountsAccountId | null;

  wfs_service_id?: WfsServicesWfsServiceId | null;

  name?: string | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.wfs_service_layers */
export interface WfsServiceLayersMutator {
  wfs_service_layer_id?: WfsServiceLayersWfsServiceLayerId;

  account_id?: AccountsAccountId | null;

  wfs_service_id?: WfsServicesWfsServiceId | null;

  name?: string | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
