// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FieldTypesFieldTypeId } from './FieldTypes';
import type { WidgetTypesWidgetTypeId } from './WidgetTypes';

/** Identifier type for public.widgets_for_fields */
export type WidgetsForFieldsWidgetForFieldId = string & { __brand: 'public.widgets_for_fields' };

/** Represents the table public.widgets_for_fields */
export default interface WidgetsForFields {
  widget_for_field_id: WidgetsForFieldsWidgetForFieldId;

  field_type_id: FieldTypesFieldTypeId | null;

  widget_type_id: WidgetTypesWidgetTypeId | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.widgets_for_fields */
export interface WidgetsForFieldsInitializer {
  /** Default value: uuid_generate_v7() */
  widget_for_field_id?: WidgetsForFieldsWidgetForFieldId;

  field_type_id?: FieldTypesFieldTypeId | null;

  widget_type_id?: WidgetTypesWidgetTypeId | null;

  label?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.widgets_for_fields */
export interface WidgetsForFieldsMutator {
  widget_for_field_id?: WidgetsForFieldsWidgetForFieldId;

  field_type_id?: FieldTypesFieldTypeId | null;

  widget_type_id?: WidgetTypesWidgetTypeId | null;

  label?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
