// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.widget_types */
export type WidgetTypesWidgetTypeId = string & { __brand: 'public.widget_types' };

/** Represents the table public.widget_types */
export default interface WidgetTypes {
  widget_type_id: WidgetTypesWidgetTypeId;

  name: string | null;

  needs_list: boolean | null;

  sort: number | null;

  comment: string | null;

  label: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.widget_types */
export interface WidgetTypesInitializer {
  /** Default value: uuid_generate_v7() */
  widget_type_id?: WidgetTypesWidgetTypeId;

  name?: string | null;

  /** Default value: false */
  needs_list?: boolean | null;

  sort?: number | null;

  comment?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.widget_types */
export interface WidgetTypesMutator {
  widget_type_id?: WidgetTypesWidgetTypeId;

  name?: string | null;

  needs_list?: boolean | null;

  sort?: number | null;

  comment?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
