// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';
import type { WmsServicesWmsServiceId } from './WmsServices';

/** Identifier type for public.wms_layers */
export type WmsLayersWmsLayerId = string & { __brand: 'public.wms_layers' };

/**
 * Represents the table public.wms_layers
 * Goal: Bring your own wms layers. Not versioned (not recorded and only added by manager).
 */
export default interface WmsLayers {
  wms_layer_id: WmsLayersWmsLayerId;

  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId;

  wms_service_id: WmsServicesWmsServiceId | null;

  wms_service_layer_name: string | null;

  label: string | null;

  /** Size of locally saved image data */
  local_data_size: number | null;

  /** Array of bounds and their size of locally saved image data */
  local_data_bounds: unknown | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/**
 * Represents the initializer for the table public.wms_layers
 * Goal: Bring your own wms layers. Not versioned (not recorded and only added by manager).
 */
export interface WmsLayersInitializer {
  /** Default value: uuid_generate_v7() */
  wms_layer_id?: WmsLayersWmsLayerId;

  account_id?: AccountsAccountId | null;

  project_id: ProjectsProjectId;

  wms_service_id?: WmsServicesWmsServiceId | null;

  wms_service_layer_name?: string | null;

  label?: string | null;

  /** Size of locally saved image data */
  local_data_size?: number | null;

  /** Array of bounds and their size of locally saved image data */
  local_data_bounds?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/**
 * Represents the mutator for the table public.wms_layers
 * Goal: Bring your own wms layers. Not versioned (not recorded and only added by manager).
 */
export interface WmsLayersMutator {
  wms_layer_id?: WmsLayersWmsLayerId;

  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId;

  wms_service_id?: WmsServicesWmsServiceId | null;

  wms_service_layer_name?: string | null;

  label?: string | null;

  /** Size of locally saved image data */
  local_data_size?: number | null;

  /** Array of bounds and their size of locally saved image data */
  local_data_bounds?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
