// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { ProjectsProjectId } from './Projects';

/** Identifier type for public.wms_services */
export type WmsServicesWmsServiceId = string & { __brand: 'public.wms_services' };

/** Represents the table public.wms_services */
export default interface WmsServices {
  wms_service_id: WmsServicesWmsServiceId;

  account_id: AccountsAccountId | null;

  project_id: ProjectsProjectId;

  url: string | null;

  image_formats: unknown | null;

  image_format: string | null;

  version: string | null;

  info_formats: unknown | null;

  info_format: string | null;

  default_crs: string | null;

  created_at: Date;

  updated_at: Date;

  updated_by: string | null;
}

/** Represents the initializer for the table public.wms_services */
export interface WmsServicesInitializer {
  /** Default value: uuid_generate_v7() */
  wms_service_id?: WmsServicesWmsServiceId;

  account_id?: AccountsAccountId | null;

  project_id: ProjectsProjectId;

  url?: string | null;

  image_formats?: unknown | null;

  image_format?: string | null;

  version?: string | null;

  info_formats?: unknown | null;

  info_format?: string | null;

  default_crs?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  updated_by?: string | null;
}

/** Represents the mutator for the table public.wms_services */
export interface WmsServicesMutator {
  wms_service_id?: WmsServicesWmsServiceId;

  account_id?: AccountsAccountId | null;

  project_id?: ProjectsProjectId;

  url?: string | null;

  image_formats?: unknown | null;

  image_format?: string | null;

  version?: string | null;

  info_formats?: unknown | null;

  info_format?: string | null;

  default_crs?: string | null;

  created_at?: Date;

  updated_at?: Date;

  updated_by?: string | null;
}
