/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as DataIndexImport } from './routes/data/index'
import { Route as PathlessLayoutIndexImport } from './routes/_pathlessLayout.index'
import { Route as PathlessLayoutDocsImport } from './routes/_pathlessLayout.docs'

// Create/Update Routes

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const DataIndexRoute = DataIndexImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutIndexRoute = PathlessLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRoute,
} as any)

const PathlessLayoutDocsRoute = PathlessLayoutDocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PathlessLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/docs': {
      id: '/_pathlessLayout/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof PathlessLayoutDocsImport
      parentRoute: typeof PathlessLayoutImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexImport
      parentRoute: typeof PathlessLayoutImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface PathlessLayoutRouteChildren {
  PathlessLayoutDocsRoute: typeof PathlessLayoutDocsRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutDocsRoute: PathlessLayoutDocsRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PathlessLayoutRouteWithChildren
  '/docs': typeof PathlessLayoutDocsRoute
  '/': typeof PathlessLayoutIndexRoute
  '/data': typeof DataIndexRoute
}

export interface FileRoutesByTo {
  '/docs': typeof PathlessLayoutDocsRoute
  '/': typeof PathlessLayoutIndexRoute
  '/data': typeof DataIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/docs': typeof PathlessLayoutDocsRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/data/': typeof DataIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/docs' | '/' | '/data'
  fileRoutesByTo: FileRoutesByTo
  to: '/docs' | '/' | '/data'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/docs'
    | '/_pathlessLayout/'
    | '/data/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DataIndexRoute: typeof DataIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DataIndexRoute: DataIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_pathlessLayout",
        "/data/"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx",
      "children": [
        "/_pathlessLayout/docs",
        "/_pathlessLayout/"
      ]
    },
    "/_pathlessLayout/docs": {
      "filePath": "_pathlessLayout.docs.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/": {
      "filePath": "_pathlessLayout.index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/data/": {
      "filePath": "data/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
