/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as LayoutDocsImport } from './routes/_layout.docs'
import { Route as DataAuthLayoutRouteImport } from './routes/data/_authLayout/route'
import { Route as DataAuthLayoutProjectsIndexImport } from './routes/data/_authLayout/projects/index'
import { Route as DataAuthLayoutAuthLayoutAuthImport } from './routes/data/_authLayout/_authLayout.auth'

// Create Virtual Routes

const DataImport = createFileRoute('/data')()

// Create/Update Routes

const DataRoute = DataImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDocsRoute = LayoutDocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LayoutRoute,
} as any)

const DataAuthLayoutRouteRoute = DataAuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => DataRoute,
} as any)

const DataAuthLayoutProjectsIndexRoute =
  DataAuthLayoutProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => DataAuthLayoutRouteRoute,
  } as any)

const DataAuthLayoutAuthLayoutAuthRoute =
  DataAuthLayoutAuthLayoutAuthImport.update({
    id: '/_authLayout/auth',
    path: '/auth',
    getParentRoute: () => DataAuthLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataImport
      parentRoute: typeof rootRoute
    }
    '/data/_authLayout': {
      id: '/data/_authLayout'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataAuthLayoutRouteImport
      parentRoute: typeof DataRoute
    }
    '/_layout/docs': {
      id: '/_layout/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof LayoutDocsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/data/_authLayout/_authLayout/auth': {
      id: '/data/_authLayout/_authLayout/auth'
      path: '/auth'
      fullPath: '/data/auth'
      preLoaderRoute: typeof DataAuthLayoutAuthLayoutAuthImport
      parentRoute: typeof DataAuthLayoutRouteImport
    }
    '/data/_authLayout/projects/': {
      id: '/data/_authLayout/projects/'
      path: '/projects'
      fullPath: '/data/projects'
      preLoaderRoute: typeof DataAuthLayoutProjectsIndexImport
      parentRoute: typeof DataAuthLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutDocsRoute: typeof LayoutDocsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDocsRoute: LayoutDocsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DataAuthLayoutRouteRouteChildren {
  DataAuthLayoutAuthLayoutAuthRoute: typeof DataAuthLayoutAuthLayoutAuthRoute
  DataAuthLayoutProjectsIndexRoute: typeof DataAuthLayoutProjectsIndexRoute
}

const DataAuthLayoutRouteRouteChildren: DataAuthLayoutRouteRouteChildren = {
  DataAuthLayoutAuthLayoutAuthRoute: DataAuthLayoutAuthLayoutAuthRoute,
  DataAuthLayoutProjectsIndexRoute: DataAuthLayoutProjectsIndexRoute,
}

const DataAuthLayoutRouteRouteWithChildren =
  DataAuthLayoutRouteRoute._addFileChildren(DataAuthLayoutRouteRouteChildren)

interface DataRouteChildren {
  DataAuthLayoutRouteRoute: typeof DataAuthLayoutRouteRouteWithChildren
}

const DataRouteChildren: DataRouteChildren = {
  DataAuthLayoutRouteRoute: DataAuthLayoutRouteRouteWithChildren,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/data': typeof DataAuthLayoutRouteRouteWithChildren
  '/docs': typeof LayoutDocsRoute
  '/': typeof LayoutIndexRoute
  '/data/auth': typeof DataAuthLayoutAuthLayoutAuthRoute
  '/data/projects': typeof DataAuthLayoutProjectsIndexRoute
}

export interface FileRoutesByTo {
  '/data': typeof DataAuthLayoutRouteRouteWithChildren
  '/docs': typeof LayoutDocsRoute
  '/': typeof LayoutIndexRoute
  '/data/auth': typeof DataAuthLayoutAuthLayoutAuthRoute
  '/data/projects': typeof DataAuthLayoutProjectsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/data': typeof DataRouteWithChildren
  '/data/_authLayout': typeof DataAuthLayoutRouteRouteWithChildren
  '/_layout/docs': typeof LayoutDocsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/data/_authLayout/_authLayout/auth': typeof DataAuthLayoutAuthLayoutAuthRoute
  '/data/_authLayout/projects/': typeof DataAuthLayoutProjectsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/data' | '/docs' | '/' | '/data/auth' | '/data/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/data' | '/docs' | '/' | '/data/auth' | '/data/projects'
  id:
    | '__root__'
    | '/_layout'
    | '/data'
    | '/data/_authLayout'
    | '/_layout/docs'
    | '/_layout/'
    | '/data/_authLayout/_authLayout/auth'
    | '/data/_authLayout/projects/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  DataRoute: typeof DataRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  DataRoute: DataRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/data"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/docs",
        "/_layout/"
      ]
    },
    "/data": {
      "filePath": "data/_authLayout",
      "children": [
        "/data/_authLayout"
      ]
    },
    "/data/_authLayout": {
      "filePath": "data/_authLayout/route.tsx",
      "parent": "/data",
      "children": [
        "/data/_authLayout/_authLayout/auth",
        "/data/_authLayout/projects/"
      ]
    },
    "/_layout/docs": {
      "filePath": "_layout.docs.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/data/_authLayout/_authLayout/auth": {
      "filePath": "data/_authLayout/_authLayout.auth.tsx",
      "parent": "/data/_authLayout"
    },
    "/data/_authLayout/projects/": {
      "filePath": "data/_authLayout/projects/index.tsx",
      "parent": "/data/_authLayout"
    }
  }
}
ROUTE_MANIFEST_END */
